<p>Vitajte $FIRSTNAME$,</p>
<p>Váš vklad bol úspešne dokončený.</p>
<p><span style="font-size: medium;"><strong style="color: #ff3366;">Prosím, klikňite "Refresh" tlačidlo(NIE tlačidlo internetového prehliadača) na stránke pre znovu načítanie zostatku.</strong></span></p>
<p>Ak máte akúkoľvek otázku, prosím neváhajte kontaktovať <a href="mailto:[Metadata:htmlencode(/Metadata/Settings.Email_SupportAddress)]">[Metadata:htmlencode(/Metadata/Settings.Email_SupportAddress)]</a>.</p>
<p>S pozdravom,<br /> [Metadata:htmlencode(/Metadata/Settings.Operator_DisplayName)] tím</p>

