<ol>
<li><strong>ÚVOD:</strong>
<p>1.1.&nbsp;&nbsp; &nbsp; Používáním a / nebo navštívením jakékoliv části webových stránek&nbsp; [Metadata:htmlencode(/Metadata/Settings.Operator_DisplayName)] (dále jen „Webové stránky“); nebo založením účtu na webových stránkách souhlasíte s následujícími ustanoveními: 
Všeobecné obchodní podmínky, uvedenými na této stránce; Zásady ochrany osobních údajů, veškerá pravidla her, veškeré podmínky akcí, bonusů a speciálních nabídek, které se někdy mohou být nalezeny na internetových stránkách. Všechny výše uvedené podmínky budou nadále souhrnně nazývány jen jako „Podmínky“. Přečtěte si Podmínky pozorně před jejich schválením. Pokud nesouhlasíte a nechcete být vázáni Podmínkami, neotevírejte si účet či nadále nepoužívejte Webové stránky. Dalším používání Webových stránek vyjadřujete svůj souhlas s podmínkami. Tyto Podmínky vstoupí v platnost dne&nbsp; 16. června 2010.</p>
</li>
<li><strong>STRANY</strong>
<p>2.1. Společnost I-Services N.V. se sídlem na adrese E-Commerce Park, Vredenburg, Curacao pod registračním číslem 104867, vlastní a provozuje&nbsp;&nbsp; &nbsp;exbeteu.com. </p>
</li>
<li><strong>ZMĚNY V PODMÍNKÁCH </strong>
<p>3.1.&nbsp;&nbsp; &nbsp; Společnost může změnit Podmínky z celé řadu důvodů, včetně obchodních důvodů, dále pro sladění znění s novými zákony a předpisy, nebo z důvodů větší podpory zákazníků. Aktuální verze Podmínek je k nalezení zde společně s datem, kdy vešly v platnost. V případě provedení změn Podmínek vás o konkrétních změnách budeme informovat pomocí emailu či umístěním oznámení na Webových stránkách.</p>
</li>
<li><strong>ZALOŽENÍ ÚČTU</strong>
<p>4.1.&nbsp;&nbsp; &nbsp; . K tomu, abyste mohli začít sázet prostřednictvím Webových stránek, musíte si založit účet na webových stránkách („Váš Účet“). Z různých právních a obchodních důvodů nedovolujeme otevřít či používat účty osobám sídlícím v určitých oblastech, včetně Spojených států amerických. Žijete-li v těchto oblastech, nemůžete si založit účet či používat Webové stránky.
 <br />4.2.&nbsp;&nbsp; &nbsp; Aby bylo možné otevřít Váš účet a mohli jste začít používat Webové stránky, obraťte se na zákaznickou podporu pomocí emailu  <a target="_blank" href="mailto:support@exclusivebet.eu">support@exclusivebet.eu</a>. 
<br />4.3.&nbsp;&nbsp; &nbsp; . Při otevření účtu budete požádáni o poskytnutí osobních údajů, včetně vašeho jména, data narození, a aktuálních kontaktních údajů, včetně adresy, telefonního čísla a e-mailové adresy („Vaše kontaktní údaje“).  <br />4.4.&nbsp;&nbsp; &nbsp; Využíváním služeb poskytovaných na Webových stránkách berete na vědomí a přijímáte fakt, že můžete vyhrát i prohrát peníze. <br />4.5.&nbsp;&nbsp; &nbsp; Váš účet musí být registrován pod vlastním správným jménem. Pro účel sázení si můžete otevřít pouze jeden účet. Jakékoliv jiné účty, které otevřete pro účel využívání námi poskytovaných služeb, budou považovány za „duplicitní“ účty. Jakékoliv duplicitní účty mohou být uzavřeny s okamžitou platností z naší strany a:<br />4.5.1.&nbsp;&nbsp; &nbsp; Všechny transakce provedené z duplicitního účtu bude neplatné;<br />4.5.2.&nbsp;&nbsp; &nbsp; Všechny sázky nebo vklady, provedené pomocí duplicitního účtu budou vráceny;  <br />4.5.3.&nbsp;&nbsp; &nbsp; Všechny vrácené peníze, výhry nebo bonusy, které jste získali nebo nabyli v průběhu doby, kdy byl duplicitní účet otevřen, Vám propadají a mohou být námi požadovány zpět. Na požádání vrátíte všechny takovéto prostředky, získané z duplicitního účtu.<br />4.6.&nbsp;&nbsp; &nbsp; Chcete-li otevřít další účet, můžete se obrátit na správce na emailu <a target="_blank" href="mailto:support@exclusivebet.eu">support@exclusivebet.eu</a>. Pokud si otevřete nový účet, starý účet bude uzavřen. <br />4.7.&nbsp;&nbsp; &nbsp; Musíte udržovat svůj účet a data na něm uvedená aktuální.</p>
</li>
<li><strong> OVĚŘENÍ VAŠÍ IDENTITY; PRANÍ ŠPINAVÝCH PENĚZ</strong>
<p>5.1.&nbsp;&nbsp; &nbsp; Tímto se zaručujete, že: <br />5.1.1.&nbsp;&nbsp; &nbsp; Nejste mladší:<br />5.1.1.1.&nbsp;&nbsp; &nbsp; 18 (osmnácti) let; nebo<br />5.1.1.2.&nbsp;&nbsp; &nbsp; než je jakýkoli zákonný věk, požadovaný zákonem a místní jurisdikcí pro veškeré hazardní hry nebo herní činnosti (dále jen „zletilost“);<br />5.1.2.&nbsp;&nbsp; &nbsp; Údaje poskytnuté při otevření účtu jsou správné; <br />5.1.3.&nbsp;&nbsp; &nbsp; . Jste právoplatným vlastníkem peněz na vašem účtu. <br />5.2.&nbsp;&nbsp; &nbsp; Souhlasem s Podmínkami nás povolujete provádět kontroly (dále „Kontroly“) vaší totožnosti a kontaktních údajů pro potřebu jak naší, či dle požadavků třetích stran (včetně regulačních orgánů). <br />5.3.&nbsp;&nbsp; &nbsp; V průběhu provádění kontrol můžeme omezit čerpání finančních prostředků z vašeho účtu.  <br />5.4.&nbsp;&nbsp; &nbsp; Za určitých okolností vás budeme kontaktovat a požádat o poskytnutí dalších informací pro úspěšné dokončení kontroly. Pokud nám neposkytnete nebo nemůže poskytnout takové informace, vyhrazujeme si právo pozastavit Váš účet, dokud nám neposkytnete požadované informace, případně můžeme trvale uzavřít váš účet. Pokaždé když budete chtít provést výběr peněžních prostředků ve výši dva tisíce tři sta eur (2300 EUR) nebo více, budete muset prokázat svou totožnost. <br />5.5.&nbsp;&nbsp; &nbsp; Pokud se nám nepodaří prokázat, že jste plnoletí, můžeme pozastavit Váš účet. Pokud se prokáže, že jste nedosáhli tohoto věku v době, kdy jste se účastnili hraní či jste prováděli transakce v nějaké z hazardních her, pak:<br />5.5.1.&nbsp;&nbsp; &nbsp; Váš účet bude uzavřen;<br />5.5.2.&nbsp;&nbsp; &nbsp; Všechny provedené transakce uzavřené vámi jako nezletilým hráčem budou neplatné, a všechny související prostředky, které jste vložil, Vám budou vráceny; <br />5.5.3.&nbsp;&nbsp; &nbsp; Jakékoli sázky, které jste uzavřel jako nezletilý, se vám vrátí;  <br />5.5.4.&nbsp;&nbsp; &nbsp; Jakékoliv výhry, které jste nabyl během této doby, Vám propadnou a vrátíte nám všechny prostředky, které byly vyplaceny z vašeho účtu.
 <br />5.5.5.&nbsp;&nbsp; &nbsp; Jako opatření proti praní špinavých peněz budou muset být veškeré vložené peníze nejméně jednou vsazeny, než bude možné požádat o jejich vyplacení. Toto pravidlo se vztahuje také na &ldquo; zrušené transakce &rdquo;.</p>
</li>
<li><strong> UŽIVATELSKÉ JMÉNO, HESLO A INFORMACE O ZÁKAZNÍCÍCH </strong>
<p>6.1.&nbsp;&nbsp; &nbsp; Po otevření Vašeho účtu, nesdělujte (ať už úmyslně nebo neúmyslně) vaše uživatelské jméno a heslo nikomu jinému. Pokud jste ztratili nebo zapomněli své údaje o účtu, můžete získat heslo kliknutím na odkaz &ldquo; Zapomenuté heslo&rdquo; , který najdete na přihlašovací stránce.</p>
</li>
<li><strong>VKLADY A VÝBĚRY Z ÚČTU </strong>
<p>7.1.&nbsp;&nbsp; &nbsp; Pokud chcete sázet nebo hrát na Webových stránkách, musíte nejdříve vložit na svůj účet peníze, které pak můžete použít na sázky či hraní her.
  <br />7.2.&nbsp;&nbsp; &nbsp; Vklady a výběry do z účtu lze provést pomocí různých poskytovatelů plateb, kteří se však mohou čas od času měnit. V rámci jednotlivých poskytovatelů se postupy a podmínky mohou lišit. Neakceptujeme peníze v hotovosti.
  <br />7.3.&nbsp;&nbsp; &nbsp; Uložením peníz souhlasíte s tím, že nebudete platby zpětně rušit, či jakkoliv zpětně požadovat peníze vložené na váš účet, a souhlasíte s tím, že případné neproplacené vklady nám budete plně kompenzovat.
 <br />7.4.&nbsp;&nbsp; &nbsp; Váš účet není vedený jako účet v bance, a proto není pojištěný, ani není nijak zajištěný, ani jinak chráněný bankovního systémem pojištění. Krom toho, peníze uloženy u nás na Vašem účtu nebudou nijak zhodnocovány.
 <br />7.5.&nbsp;&nbsp; &nbsp; Můžeme kdykoliv odebrat část kladného zůstatku na vašem účtu, abychom pokryli splacení odpovídající částky, kterou nám dlužíte po vyrovnání účtů, vztahujících se k duplicitním účtům, tajným dohodám, klamání, podvodům, jakýmkoliv kriminálním aktivitám či chybám. 
 <br />7.6.&nbsp;&nbsp; &nbsp; Jste zodpovědní za nahlášení svých výher a ztrát pro účely odvedení daňové povinnosti v místě konané aktivity či pro účely jiných pověřených orgánů.
 <br />7.7.&nbsp;&nbsp; &nbsp; Kdykoliv můžete požádat o čerpání prostředků z účtu, za předpokladu, že:
 <br />7.7.1.&nbsp;&nbsp; &nbsp; všechny platby provedené z Vašeho účtu byly potvrzeny jako proběhlé a žádná nebyla stažena zpět, vymazána či jinak zrušena;
 <br />7.7.2.&nbsp;&nbsp; &nbsp; všechny Kontroly, uvedené výše v odstavci 5, byly dokončeny.
  <br />7.8.&nbsp;&nbsp; &nbsp; Pokud jsme schválili vyplacení peněz, musíte nám poskytnout dostatek informací o tom, jakým způsobem by měly být finanční prostředky vyplaceny. Pokusíme se vyhovět vaší žádosti, pokud jde o způsob platby a druh měny výplaty vašich prostředků. Vyhrazujeme si právo zvolit způsob platby a druh měny výplaty prostředků.
 <br />7.9.&nbsp;&nbsp; &nbsp; Vyhrazujeme si právo účtovat poplatek ve výši vlastních nákladů (včetně nákladů na vklad) v případě vyplacení finančních prostředků, které nebyly vloženy do hry.</p>
</li>
<li><strong>UZAVÍRÁNÍ SÁZEK A HRANÍ </strong>
<p>8.1.&nbsp;&nbsp; &nbsp; Všechny transakce budou uzavřeny v jazyce, v němž jste umístili vaši transakci. <br />8.2.&nbsp;&nbsp; &nbsp; Je vaší povinností zajistit, aby údaje o každé transakci byli správné.
 <br />8.3.&nbsp;&nbsp; &nbsp; Na Webových stránkách máte přístup k transakční historii. <br />8.4.&nbsp;&nbsp; &nbsp; Vyhrazujeme si právo kdykoliv odmítnout jakoukoliv vámi požadovanou transakci nebo její část podle našeho vlastního uvážení. Nepřijmeme žádnou transakci, dokud od nás nedostanete potvrzení, že byla přijata. Pokud nedostanete potvrzení, že byla transakce přijata, kontaktujte Zákaznický servis. <br />8.5.&nbsp;&nbsp; &nbsp; Jakmile je vaše sázka potvrzena, nemůžete transakci zrušit bez našeho písemného souhlasu. </p>
</li>
<li><strong>TAJNÉ DOHODY, PODVÁDĚNÍ, PODVODY A TRESTNÁ ČINNOST </strong>
<p>9.1.&nbsp;&nbsp; &nbsp; Tyto následující činnosti nejsou dovoleny a představují závažné porušení podmínek: <br />&bull;&nbsp;&nbsp; &nbsp; domlouvaní se s třetími stranami;
 <br />&bull;&nbsp;&nbsp; &nbsp; použití neoprávněné výhodu nebo vlivu (běžně známého jako podvádění), včetně využívání jiných chyb, mezer nebo nedostatků našeho programu, použití automatizovaných hráčů (někdy nazývané jako „roboty“); nebo využívání z „chybného nastavení“;
 <br />&bull;&nbsp;&nbsp; &nbsp; provádění podvodných aktivit ve vlastní prospěch, včetně použití ukradených, kopírovaných nebo jinak neoprávněně získaných kreditních či debetních karet, jako zdroj finančních prostředků;
 <br />&bull;&nbsp;&nbsp; &nbsp; účast na případné trestné činnosti, včetně praní špinavých peněz a spáchání trestného činu s trestní následky. <br />9.2.&nbsp;&nbsp; &nbsp; Přijmeme veškerá přiměřená opatření k zabránění těchto činností, odhalení příslušných subjektů, náležité vypořádání se s příslušnými hráči. Neneseme zodpovědnost za jakékoli ztráty nebo škody, které mohou vzniknout vám nebo jakémukoliv jinému hráči v důsledku podvádění, podvodné nebo jinak nezákonné činnosti, a jakákoliv opatření podnikneme, záleží pouze na našem uvážení. <br />9.3.&nbsp;&nbsp; &nbsp; Máte-li podezření, že někdo nejedná podle ustanovených dohod, podvádí, nebo provádí nezákonnou činnost, musíte nám tento fakt co nejdříve oznámit posláním e-mailu. 
 <br />9.4.&nbsp;&nbsp; &nbsp; Vyhrazujeme si právo informovat příslušné orgány, jiné provozovatele on-line hracích serverů nebo provozovatelům hazardních her, ostatním poskytovatelům on-line služeb a bankám, společnostem vydávajícím kreditní karty, elektronickým poskytovatelům platebních nebo jiných finančních institucí o vaší totožnosti v případě jakékoliv podezření na nezákonné, podvodné nebo nepatřičné činnosti. Vy souhlasíte s tím, že budete plně spolupracovat při vyšetřování takovéto činnosti. </p>
</li>
<li><strong>DALŠÍ NEPOVOLENÉ AKTIVITY </strong>
<p>10.1.&nbsp;&nbsp; &nbsp; Neměli byste používat Webové stránky pro jakýkoliv jednání, které je považováno za hanlivé, urážlivé, obscénní, rasistické, sexistické, diskriminační, nebo útočné. Nesmíte používat urážlivý nebo agresivní jazyk či vyobrazení; nadávat, vyhrožovat, obtěžovat či zneužívat jiné osoby, včetně jiných uživatelů, nebo se chovat takovým způsobem vůči jakémukoliv zaměstnanci společnosti, kteří pracují pro Webové stránky nebo pro Zákaznický servis. <br />10.2.&nbsp;&nbsp; &nbsp; Nebudete poškozovat Webové stránky, zaplavovat webové stránky s informacemi, což by mohlo omezit jejich funkčnost, ani nebudete v žádném případě používat funkce, které mohou mít vliv na funkci webových stránek jako například šíření virů, „worms“, „logical bombs“ nebo podobné. Jakékoliv zmnožené transakce nebo „spam“ jsou přísně zakázány. Nesmíte zasahovat nebo jakkoliv manipulovat, odstraňovat nebo jakýmkoliv způsobem měnit jakékoli informace v jakékoli formě, která je obsažena na těchto stránkách. <br />10.3.&nbsp;&nbsp; &nbsp; Budete používat webové stránky pouze pro osobní zábavu. Není povoleno reprodukovat webové stránky nebo jakékoli jejich části v jakékoli formě, bez našeho výslovného souhlasu. <br />10.4.&nbsp;&nbsp; &nbsp; . Je zakázáno získávat neoprávněného přístupu k webovým stránkám, serverům, na kterém je webová stránka uložena, nebo jakýkoliv server, počítač nebo databázi připojené na webové stránky. Je zakázáno útočit na webové stránky prostřednictvím útoku denial-of-service a podobně. Při porušení tohoto ustanovení budeme hlásit každé takovéto porušení příslušným orgánům činným v trestním řízení a budeme spolupracovat s těmito orgány tím, že jim zveřejníme vaší totožnost. V případě takového porušení bude okamžitě ukončeno vaše právo na používání webových stránek. <br />10.5.&nbsp;&nbsp; &nbsp; Neneseme odpovědnost za jakékoli ztráty nebo škody způsobené distribucí útoku typu denial-of-service, šířením virů nebo jiných technologicky škodlivých materiálů, které mohou infikovat počítače, počítačové programy, data nebo jiné osobní materiály z důvodu vašeho používání Webových stránek z důvodu vašeho stahování materiálů, zveřejněných na takovýchto webových stránkách, nebo na jakékoliv webové stránce napojené na internetovou stránku. <br />10.6.&nbsp;&nbsp; &nbsp; Je zakázáno prodávat nebo převádět účty mezi hráči, či záměrně prohrávat za záměrem převodu žetonů jinému hráči. Úmyslná prohra nastává, pokud prohrajete za účelem převedení žetonů či peněz na účet jiného uživatele. </p>
</li>
<li><strong>UZAVŘENÍ A UKONČENÍ Z NAŠÍ STRANY </strong>
<p>11.1.&nbsp;&nbsp; &nbsp; Pokud a vašem účtu neproběhla žádná transakce po dobu 30 měsíců a váš účet je „neaktivní“, vrátíme vám zůstatek na vašem účtu a účet uzavřeme. <br />11.2.&nbsp;&nbsp; &nbsp; Váš neaktivní účet bude ukončen písemným oznámením (nebo pokusem o oznámení), pomocí kontaktních údajů. V případě takového ukončení z naší strany, krom důvodů pro ukončení vyjmenovaných podle odstavce 11 (tajná dohoda, podvádění, podezřelé sázky, podvody a trestná činnosti), nebo podle odstavce 20 (porušení Podmínek) těchto Podmínek, vám vrátíme zůstatek vašeho účtu. Pokud vás nelze nalézt, finanční prostředky budou poukázány příslušnému orgánu, pod nějž příslušností hazardu spadá. </p>
</li>
<li><strong>ZMĚNY NA WEBU </strong>
<p>12.1.&nbsp;&nbsp; &nbsp; Dle vlastního uvážení můžeme kdykoliv měnit obsah nebo změnit jakýkoliv produkt nabízený prostřednictvím Webových stránek za účelem udržování Webové stránky. &nbsp;</p>
</li>
<li><strong>SELHÁNÍ IT TECHNOLOGIE </strong>
<p>13.1.&nbsp;&nbsp; &nbsp; V případě neočekávané systémové vady, poruchy nebo vyskytující se chyby v softwaru nebo hardwaru, který používáme, učiníme okamžité kroky k nápravě tohoto problému. Nepřijímáme žádnou odpovědnost za selhání IT, které jsou způsobeny vaším vybavení používaného pro přístup na Webové stránky, nebo chyby, které se týkají vašeho poskytovatele internetových služeb. </p>
</li>
<li><strong>CHYBY NEBO OPOMENUTÍ </strong>
<p>14.1.&nbsp;&nbsp; &nbsp; Řada okolností může zapříčinit vznik chyby z naší strany v době uzavírání sázky nebo platby. Vyhrazujeme si právo zrušit jakoukoli sázku provedenou na zjevně nesprávné kurzy, přehozené kurzy (kde se uvedené kurzy týkají špatných týmů), nebo pokud je sázka podána až po začátku události, pokud daná událost není k dispozici pro on-line sázky. exbeteu.com si vyhrazuje právo odmítnout, omezit, zrušit nebo omezit všechny sázky. Ani my (včetně našich zaměstnanců nebo zástupců), ani naši smluvní partneři nebo dodavatelé nenesou zodpovědnost za jakékoliv ztráty, včetně ztráty výher, které vyplývají z chyb z naší strany či vašeho omylu. Jakékoliv výhry / ztráty vycházející z takovéto chyby vám budou odebrány. </p>
</li>
<li><strong>VYLOUČENÍ ODPOVĚDNOSTI </strong>
<p>15.1.&nbsp;&nbsp; &nbsp; Váš přístup a využívání produktů nabízených prostřednictvím Webové stránky je výlučně věcí vaší volby, vašeho zvážení a na vaší vlastní zodpovědnost.  <br />15.2.&nbsp;&nbsp; &nbsp; Poskytneme odpovídající péči a servis Webovým stránkám tak, jak je popsáno v těchto Podmínkách. Neslibujeme nic jiného, ani neposkytujeme žádné další záruky vztahující se na Webové stránky samotné, nebo na výrobky nabízené prostřednictvím Webových stránek, a tímto vylučujeme (v rozsahu povoleném zákonem) veškeré záruky týkající se téhož. <br />15.3.&nbsp;&nbsp; &nbsp; Neneseme odpovědnost vůči Vám v rámci smlouvy, deliktu (včetně nedbalosti) nebo jakékoliv obchodní ztráty, včetně ztráty dat, zisku, příjmů, podnikání, příležitostí, dobrého jména, pověsti nebo přerušení činnosti, nebo jakékoliv ztráty, které nejsou v současné době předvídatelné, jak vyplývá z Podmínek nebo z vašeho používání Webových stránek. </p>
</li>
<li><strong>PORUŠENÍ PODMÍNEK </strong>
<p>16.1.&nbsp;&nbsp; &nbsp; Budete nám kompenzovat jakékoliv nároky, závazky, náklady, náklady (včetně právních poplatků) a jiných poplatků, které mohou vzniknout v důsledku vašeho porušení podmínek v plné výši. <br />16.2.&nbsp;&nbsp; &nbsp; Pokud jste vážně porušili smluvní podmínky, vyhrazujeme si právo, ale nikoliv povinnost:
 <br />16.2.1.&nbsp;&nbsp; &nbsp; Poskytnout vám oznámení (prostřednictvím udaných kontaktních údajů), že jste se dostali do rozporu s Podmínkami, které vyžadují přerušení činnosti nebo naopak nekonání, <br />16.2.2.&nbsp;&nbsp; &nbsp; Pozastavit váš účet tak, abyste nebyli schopni uzavírat sázky nebo hrát na Webových stránkách, <br />16.2.3.&nbsp;&nbsp; &nbsp; Zrušit váš účet buď na základě předchozího upozornění, či bez něj.
 <br />16.2.4.&nbsp;&nbsp; &nbsp; Vybrat z vašeho účtu částku všech výplat, bonusů nebo výher, kterých se porušení podmínek týká. 
 <br />16.3.&nbsp;&nbsp; &nbsp; Vyhrazujeme si právo zakázat jakékoliv přístupové údaje a přístupové heslo, pokud jste podle našeho názoru porušili některé z ustanovení těchto Podmínek.</p>
</li>
<li><strong>PRÁVA K DUŠEVNÍMU VLASTNICTVÍ </strong>
<p>17.1.&nbsp;&nbsp; &nbsp; Webový design, text, grafika, hudba, zvuk, fotografie, video, výběr a uspořádání výše zmíněných, softwarový balíček, základní zdrojový kód, software a všechny ostatní materiály obsažené v rámci těchto stránek podléhají autorskému právu a dalším vlastnickým právům, které buď patří nám, nebo jsou používány na základě licence od držitelů práv třetích stran. Vzhledem k tomu, že jakýkoliv materiál obsažený na webových stránkách je možné stáhnout nebo vytisknout, tento materiál lze stáhnout pouze do jednoho osobního počítače a kopie dokumentů či jejich části mohou být vytištěny pouze a výhradně pro vlastní potřebu a nekomerční použití. <br />17.2.&nbsp;&nbsp; &nbsp; . Za žádných okolností nesmí využití Webových stránek nést zisk v rámci jakýchkoli práv duševního vlastnictví (například autorských práv, know-how nebo ochranné známky), které patří nám či třetí straně.
 <br />17.3.&nbsp;&nbsp; &nbsp; Není možné za žádných okolností dále využívat či reprodukovat jakékoliv obchodní názvy, obchodní značky nebo loga, které se objevují na Webových stránkách s výjimkou případů, u nichž je to výslovně povoleno v souladu s Podmínkami.
 </p>
</li>
<li><strong>VAŠE OSOBNÍ ÚDAJE </strong>
<p>18.1.&nbsp;&nbsp; &nbsp; Ze zákona jsme povinni v souladu s požadavky na ochranu osobních údajů dodržovat způsob shromažďování osobních údaje, které jsme získali během vašeho využívání Webových stránek. Proto bereme velmi vážně své povinnosti a způsob, jakým uchováváme vaše osobní údaje. <br />18.2.&nbsp;&nbsp; &nbsp; Tím, že nám informace dáte dobrovolně, souhlasíte se zpracováním vašich osobních údajů pro účely stanovené v Podmínkách, pro provoz Webových stránek, nebo v souladu s právní a regulační povinností. <br />18.3.&nbsp;&nbsp; &nbsp; Společnost nebude zveřejňovat žádné osobní údaje nikomu jinému, než svým zaměstnancům, kteří potřebují přístup k vašim datům pro řádné poskytnutí služeb.
 <br />18.4.&nbsp;&nbsp; &nbsp; Uchováváme kopie veškerého způsobu komunikace s námi, které nám posíláte (včetně kopií veškerých e-mailů), za účelem zajištění přesnosti záznamů, které jsme od vás obdrželi. </p>
</li>
<li><strong>POUŽÍVÁNÍ COOKIES NA WEBOVÝCH STRÁNKÁCH </strong>
<p>19.1.&nbsp;&nbsp; &nbsp; Webové stránky používají „cookies“, aby bylo dosaženo větší funkčnosti stránek. Cookie je malý textový, který se stáhne do vašeho počítače při vstupu na tyto Webové stránky, který nám umožňuje poznat, když znovu vstoupíte na Webové stránky. Informace o Cookies, jejich smazání či kontrola je k dispozici na www.aboutcookies.org. Vezměte prosím na vědomí, že zrušením cookies, nebo zakázání budoucích cookies, nebudete mít přístup k určité oblasti nebo funkce webových stránek. </p>
</li>
<li><strong>STÍŽNOSTI A INFORMACE </strong>
<p>20.1.&nbsp;&nbsp; &nbsp; Pokud chcete podat stížnost týkající se Webové stránky, jako první kontaktujte Zákaznický servis. <br />20.2.&nbsp;&nbsp; &nbsp; V případě jakéhokoli sporu, souhlasíte s tím, že záznamy na serveru bude sloužit jako konečná autoritu při určování výsledku reklamace. <br />20.3.&nbsp;&nbsp; &nbsp; Souhlasíte s tím, že v nepravděpodobném případě neshody mezi výsledkem, který se objeví na vaší obrazovce a na herním server, berete na vědomí a souhlasíte s tím, že výsledky jak se jeví na serveru, dostanou prioritu a že naše záznamy budou s konečnou platností sloužit k určení podmínek a okolností vaší účasti v příslušné on-line herní aktivitě a výsledků této účasti. &ldquo;Historie tahů &rdquo; a &ldquo;Herní Chat&rdquo;se nepovažují za rozhodující záznam pro žádnou hru či službu. <br />20.4.&nbsp;&nbsp; &nbsp; Pokud vás budeme chtít kontaktovat v rámci takovéhoto sporu, uděláme to pomocí některého z vámi udaných kontaktních údajů.</p>
</li>
<li><strong>VÝKLAD</strong>
<p>21.1.&nbsp;&nbsp; &nbsp; Původní znění Podmínek je v angličtině a je nutné při jejich výkladu vycházet z původního anglického textu. Pokud jsou Podmínky nebo jakékoliv dokumenty nebo oznámení související s nimi přeloženy do jiného jazyka, za originál se považuje anglická verze.</p>
</li>
<li><strong>PŘEVOD PRÁV A POVINNOSTÍ</strong>
<p>22.1.&nbsp;&nbsp; &nbsp; Vyhrazujeme si právo převést, postoupit, licencovat nebo zastavit Podmínky, zcela nebo částečně, na jakoukoliv osobu, za předpokladu, že takový bude nadále fungovat za stejných podmínek a podmínek, které nejsou o nic méně výhodné pro vás.</p>
</li>
<li><strong>UDÁLOSTI MIMO NAŠI KONTROLU</strong>
<p>23.1.&nbsp;&nbsp; &nbsp; Neneseme odpovědnost za jakékoliv neplnění nebo zpoždění v provozování služeb, některého z našich závazků v souladu s Podmínkami, které je způsobeno událostmi mimo naši kontrolu, včetně živelných pohrom, války, občanské vzpoury, přerušení dodávek veřejných komunikačních sítí nebo služeb, průmyslových řešení sporů nebo DDOS útoků a podobných útoků z internetu, které mají nepříznivý vliv („Vyšší mocí“).  Náš provoz se pozastaví po celou dobu trvání události způsobené zásahem Vyšší moci. Budeme se snažit ukončit zásah Vyšší moci, nebo se budeme snažit najít přiměřené řešení, abychom dostáli svým závazkům navzdory zásahu Vyšší moci. </p>
</li>
<li><strong>VZDÁNÍ SE PRÁV</strong>
<p>24.1.&nbsp;&nbsp; &nbsp; Pokud se nám nepodaří vás přimět k striktnímu plnění některé z vašich povinností, nebo pokud se nám nepodaří uplatnit některé z práv nebo opravných prostředků, na které máme právo, neznamená to, že se vzdáváme těchto práv nebo nápravných opatření a nezbavuje vás to povinnosti dodržování těchto závazků. <br />24.2.&nbsp;&nbsp; &nbsp; Vzdání se některého ze základních práv v našem případě nepředstavuje automatické následné zřeknutí se dalšího práva. Žádné vzdání se práv nenabývá účinnosti, pokud není výslovně uvedeno, že se jedná o vzdání práv a nebude vám to písemně sděleno v souladu s výše uvedeným. </p>
</li>
<li><strong>ODDĚLITELNOST</strong>
<p>25.1.&nbsp;&nbsp; &nbsp; Pokud jsou některé z těchto podmínek stanoveny za neplatné, nezákonné nebo nevymahatelné v jakémkoli rozsahu, takovéto podmínky nebo ustanovení budou v tomto rozsahu odděleny od ostatních podmínek a opatření, která bude i nadále v platnosti v plném rozsahu povoleném platnými právními nařízeními. V takových případech je oddělená část považována za neplatnou nebo nevymahatelnou a mění se způsobem, který je v souladu s platnými právními předpisy, aby odrážely náš původní záměr tak přesně, jak jen je to možné.</p>
</li>
<li><strong>PRÁVO A SOUDNÍ PRAVOMOC</strong>
<p>26.1.&nbsp;&nbsp; &nbsp; Tyto Podmínky se řídí a vykládají v souladu s právními předpisy Holandských Antil. Soudy v Holandských Antil mají nevýhradní soudní pravomoc nad případnými spory vyplývající z Podmínek samotných či z využívání služeb poskytovaných na Webových stránkách.</p>
</li>
<li><strong>ODKAZY</strong>
<p>27.1.&nbsp;&nbsp; &nbsp; Tam, kde poskytujeme hypertextové odkazy na jiné webové stránky, činíme tak pouze pro informační účely. Můžete použít jakékoliv z těchto odkazů pouze na své vlastní riziko a my neneseme žádnou odpovědnost za obsah nebo používání takovýchto stránek, ani za informace na nich obsažené.</p>
</li>
</ol>
<p style="text-align: right;"><button type="button" onclick="window.print(); return false" class="button"> <span class="button_Right"> <span class="button_Left"> <span class="button_Center"> <span>Print</span> </span> </span> </span> </button></p>

