
<strong>[Metadata:htmlencode(/Metadata/Settings.Operator_DisplayName)] Smlouva s koncovým uživatelem </strong>
<br/>
<br/> PŘEČTĚTE SI PROSÍM NÁSLEDUJÍCÍ TEXT DŮKLADNĚ. DOPORUČUJEME VÁM SI TYTO PODMÍNKY VYTISKNOUT A ULOŽIT JE SPOLEČNĚ SE VŠEMI POTVRZOVACÍ E-MAILY, DODATEČNÝMI PODMÍNKAMI, DATY TRANSAKCÍ, PRAVIDLY HRY A ZPŮSOBŮ PLATEB, KTERÉ SE TÝKAJÍ VAŠEHO UŽÍVÁNÍ WEBOVÝCH STRÁNEK. NEUCHOVÁVÁME KAŽDOU JEDNOTLIVOU SMLOUVU S UŽIVATELI, TAK SI JI, PROSÍM, VYTISKNOUT PRO SVOU VLASTNÍ POTŘEBU. TYTO PRAVIDLA A PODMÍNKY PODLÉHAJÍ ZMĚNÁM BEZ PŘEDCHOZÍHO UPOZORNĚNÍ.
<br/> OZNÁMENÍ TĚCHTO PODMÍNEK PŘEDSTAVUJE NABÍDKU SLUŽEB. REGISTRACÍ SE ZAVAZUJETE K UŽÍVÁNÍ SLUŽEB, K NIMŽ SE VZTAHUJE TATO DOHODA, A DALE PROHLAŠUJETE, ŽE JSTE VE VĚKU 18 LET NEBO STARŠÍ A SOUHLASÍTE, ŽE BUDETE DORŽOVAT NÁSLEDUJÍCÍMI PODMÍNKY. POKUD NECHCETE PŘIJMOUT ZNĚNÍ TĚCHTO PODMÍNEK, NEMŮŽETE SE ZAREGISTROVAT A OTEVŘÍT SI ÚČET A NEBUDETE MOCI PŘISTUPOVAT K SOFTWARU A NABÍZENÝM HERNÍM SLUŽBÁM.
<br/>
<br/>Tato smlouva s koncovým uživatelem (dale jen "smlouva") je právním dokumentem mezi Vámi (“Vy”) a [Metadata:htmlencode(/Metadata/Settings.Operator_DisplayName)], provozovaným EveryMatrix N.V. , společností  vedenou v Curacao, a jeho připojenými společnostmi, následníky a přidělenci (zde kolektivně nazýváni "[Metadata:htmlencode(/Metadata/Settings.Operator_DisplayName)]"). Software (dále "Software") herní sslužby (dále "herní služby") jsou poskytovány [Metadata:htmlencode(/Metadata/Settings.Operator_DisplayName)] na současné bázi, pro vaše osobní užití. Poker a použitý software na [Metadata:htmlencode(/Metadata/Settings.Operator_DisplayName)] je provozován EveryMatrix NV, společností  vedenou v Curacao, s herní licence č. 8048/JAZ z listopadu 1996, č. 41.
<br/> Vezměte prosím na vědomí, že software a herní služby nejsou určeny pro osoby mladší 18 let. Nikdo mladší 18 let nesmí vsadit nebo se podílet na činnosti, na hrách, software a služeb v oblasti her (také souhrnně označovány jako "Služby") na [Metadata: HTMLEncode (/Metadata/Settings.Operator_DisplayName)] a [Metadata: HTMLEncode (/Metadata/Settings.Operator_DisplayName)], nebo nesmí být obyvatelem USA, Turecku, nebo tam, kde jsou tyto služby přísně zakázané. Pokud se [Metadata: HTMLEncode (/Metadata/Settings.Operator_DisplayName)] dozví prostřednictvím spolehlivého zdroje, že registrovaný uživatel je osoba mladší 18 let nebo mu není dovoleno využívat herních služeb, [Metadata: HTMLEncode (/Metadata/Settings.Operator_DisplayName)] mimo jiných postihů které má k dispozici, zruší účet daného uživatele.
<br/> Tato dohoda se vztahuje na jakékoliv využívání Služeb. V případě rozporu mezi ustanoveními této dohody a jakékoli ustanovení o [Metadata: HTMLEncode (/Metadata/Settings.Operator_DisplayName)] Poker sekci, ustanovení této dohody mají přednost. Pokud zde není uvedeno jinak, jinak, každý odkaz k této dohodě na [Metadata: HTMLEncode (/Metadata/Settings.Operator_DisplayName)] se považuje za to, že byl proveden vůči [Metadata: HTMLEncode (/Metadata/Settings.Operator_DisplayName)], a jeho přidruženým podnikům, či nástupcům.
<br/> Tyto Pravidla a Podmínky, společně s [Metadata: HTMLEncode (/Metadata/Settings.Operator_DisplayName)] sekcí Turnaje, sekcí Jak hrát, všemi herními pravidly, Odpojení a Storno podmínkami a všemi dalšími dodatečná pravidly a podmínkami na [Metadata: HTMLEncode (/Metadata/Settings.Operator_DisplayName)], které se specificky týkají a řídí nějakou konkrétní událost, hru, software nebo turnaj tvoří právně závaznou dohodu (dále jen "dohoda"). Pokud je tato dohoda přeložena, anglická verze textu má přednost. Jakýkoli jiný doklad připravený v souvislosti s touto smlouvou musí být v angličtině nebo musí být řádně připraven překlad do angličtiny, a I v tomto případě má anglický překlad přednost v případě jakéhokoli rozporu mezi zněními.
<br/>
<br/>
<strong>SOFTWARE</strong>
<br/>
<span style="font-weight: bold;">1.&nbsp;&nbsp; &nbsp;SOFTWAROVÁ LICENCE: </span>
<br/> [Metadata: HTMLEncode (/Metadata/Settings.Operator_DisplayName)] Vám uděluje osobní, nevýhradní, nepřenosnou licenci k používání softwaru, ale ponechává si veškerá vlastnická práva k softwaru. Všechna práva, která nejsou výslovně udělena na základě této dohody, jsou vyhrazena společnosti [Metadata: HTMLEncode (/Metadata/Settings.Operator_DisplayName)], a licenčním partnerům [Metadata: HTMLEncode (/Metadata/Settings.Operator_DisplayName)].Software je licencován pouze pro osobní použití. Vaše licence vám neuděluje žádný titul nebo vlastnictví softwaru, a neměla by být považována jako prodej jakýchkoliv práv v rámci softwaru.
<br/>
<br/>
<span style="font-weight: bold;">2.&nbsp;&nbsp; &nbsp;VLASTNICTVÍ SOFTWARU: </span>
<br/> Všechna práva, nároky, zájmy a práva k duševnímu vlastnictví Softwaru jsou ve vlastnictví [Metadata: HTMLEncode (/Metadata/Settings.Operator_DisplayName)], nebo jejích poskytovatelů licence, a mohou být chráněna příslušnými autorskými právy nebo jinými zákony o ochraně duševního vlastnictví a hraní her. Všechna práva, která nejsou výslovně udělena na základě této dohody, jsou vyhrazena společnosti [Metadata: HTMLEncode (/Metadata/Settings.Operator_DisplayName)].
<br/>
<br/>
<span style="font-weight: bold;">3.&nbsp;&nbsp; &nbsp;UŽITÍ SOFTWARU: </span>
<br/> Smíte používat software pouze v souladu s touto dohodou. Můžete instalovat software nebo jiné součásti služby na jakýchkoli další osobní počítač. Můžete si vytvořit záložní kopie softwaru za předpokladu, že takové použití a zálohování kopie je pouze pro vaše vlastní užití v souladu s touto dohodou, a dále, že takové instalace a používání se provádí pomocí počítače, ve kterém jste primární uživatel. Můžete kdykoliv použít pouze jednu kopii softwaru na jednom počítači. Není dovoleno hrát u jednoho stolu, nebo ve stejném turnaji za použití více účtů ze stejného počítačového hardwaru a pokud se tak stane, bude to považováno za přímé porušení této smlouvy.
<br/>
<br/>
<span style="font-weight: bold;">4.&nbsp;&nbsp; &nbsp;SOFTWAROVÁ OMEZENÍ:</span>
<br/> Software obsahuje materiály chráněné autorskými právy, obchodní tajemství a jiné soukromé materiály. Berete na vědomí, že Software ve formě zdrojového kódu zůstává důvěrným obchodním tajemstvím [metadat: HTMLEncode (/Metadata/Settings.Operator_DisplayName)]. Nesmíte zpětně analyzovat, dekompilovat, upravovat, veřejně zobrazovat, připravovat odvozená díla na jeho základě, rozebírat, nebo jinak reprodukovat nebo poskytovat software ostatním lidem. Nesmíte prodávat, převádět, sublicencovat, pronajímat, půjčovat, nebo přímo či nepřímo převádět software na třetí osobu. Jakékoliv akt v rozporu s touto smlouvou je neplatný.
<br/>
<br/>
<span style="font-weight: bold;">5.&nbsp;&nbsp; &nbsp;ZMĚNY VE FUNKČNOSTI SOFTWARU: </span>
<br/> Přijetím podmínek této smlouvy, souhlasíte s tím, že [Metadata: HTMLEncode (/Metadata/Settings.Operator_DisplayName)] je povoleno omezit, odepřít, aktualizovat nebo zrušit některé nebo všechny funkce tohoto softwaru kdykoli, a to bez předchozího upozornění. Souhlasíte s tím, že nesete rizika a [metadat: HTMLEncode (/Metadata/Settings.Operator_DisplayName)] nebude nest zodpovědnost za následky, které změna funkčnosti může mít na vaši schopnost používat software. [Metadata: HTMLEncode (/Metadata/Settings.Operator_DisplayName)] může vyžadovat, jako podmínku za Váš stálý přístup k služnám [metadat: HTMLEncode (/Metadata/Settings.Operator_DisplayName)], váš souhlas s vylepšení Software, jeho opravami, úpravami, konverzemi na novějších verze softwaru nebo jakékoliv jiné změny softwaru.
<br/>
<br/>
<span style="font-weight: bold;"> PODMÍNKY PROVOZU </span>
<br/>
<span style="font-weight: bold;">6.&nbsp;&nbsp; &nbsp; PŘIJETÍ PODMÍNEK:</span>
<br/> [Metadata: HTMLEncode (/Metadata/Settings.Operator_DisplayName)] vám dovoluje používat nebo přehrávat své služby, v souladu s podmínkami této dohody. Prosím, přečtěte si je pozorně. Po registraci a otevření účtu jak to předpokládá § 7 níže, potvrzujete, že souhlasíte s tím, že budete vázáni podmínkami této dohody. Pokud nechcete být vázáni těmito podmínkami, nemůžete se zaregistrovat a otevřít si účet, a nebudete moci pse přihlašovat nebo používat jakékoliv služby. Podmínky této Smlouvy mohou být změněny nebo aktualizovány kdykoli [Metadata: HTMLEncode (/Metadata/Settings.Operator_DisplayName)], bez jakéhokoliv předchozího upozornění. Vaše další řihlášení a používání služeb, znamená, že souhlasíte s tím, že budete dodržovat nejnovější verzi této smlouvy. Aktuální verzi této dohody můžete zkontrolovat kdykoli.
<br/>
<br/>
<span style="font-weight: bold;">7.&nbsp;&nbsp; &nbsp;REGISTRACE:</span>
<br/> Chcete-li využívat [metadat: HTMLEncode (/Metadata/Settings.Operator_DisplayName)] služeb, musíte si nejprve otevřít účet zadáním jedinečné a platné e-mailové adresy a přidruženého heslo. Chcete-li vložit peníze na svůj účet, musíte zadat jméno a příjmení, adresu a telefonní číslo. Souhlasíte s tím, že poskytnete pouze pravdivé a aktuální informace, a dále souhlasíte s tím, že tyto informace budete aktualizovat podle potřeby, aby byly pravdivé a aktuální. Také souhlasíte s tím, aby [Metadata: HTMLEncode (/Metadata/Settings.Operator_DisplayName)] software udělal digitální otisk vašeho počítače z bezpečnostních důvodů. Otisk se skládá ze sady čísel, včetně konfigurace IP, který je uložen spolu s informací o vašem účtu. Při otevření účtu s virtuálními penězi na [Metadata: HTMLEncode (/Metadata/Settings.Operator_DisplayName)], budete mít přístup k následujícímu: hry za peníze, turnaje s penězi. S účtem se skutečnými penězi můžete vstupovat do hry o skutečné peníze a do turnajů o skutečné peníze. Je přísně zakázáno mít více než jeden aktivní účet na [Metadata: HTMLEncode (/Metadata/Settings.Operator_DisplayName)] v jednom okamžiku. [Metadata: HTMLEncode (/Metadata/Settings.Operator_DisplayName)] si vyhrazuje právo pozastavit, změnit, odstranit a / nebo přidat jakoukoli hru podle svého vlastního uvážení s okamžitou platností a bez předchozího upozornění a [Metadata: HTMLEncode (/Metadata/Settings.Operator_DisplayName )] neponese odpovědnost za jakékoli takovéto události.
<br/>
<br/>
<span style="font-weight: bold;">8.&nbsp;&nbsp; &nbsp;OSOBNÍ VYUŽITÍ HERNÍCH SLUŽEB:</span>
<br/> Souhlasíte s tím, že budete informace o vašm účtu držet v tajnosti, a nedoolíte aby je někdo jiný používal nebo k nim měl přístup. Každá účast na hrách je věc vaší vlastní volby, rozhodnutí a je na vase riziko. Tím, že hrajete na [Metadata: HTMLEncode (/Metadata/Settings.Operator_DisplayName)], souhlasíte s tím, že nebudete považovat Služby nebo jiné aspekty [Metadata: HTMLEncode (/Metadata/Settings.Operator_DisplayName)] za urážlivé, nevhodné, nespravedlivé nebo neslušné. Můžete vsázet pouze pro svou vlastní osobní zábavu. Jakékoli komerční využití [metadat: HTMLEncode (/Metadata/Settings.Operator_DisplayName)] je přísně zakázáno. Souhlasíte s tím, že jste zodpovědný za ověřování a dodržování zákonů, jimiž se řídí regulace hazardních her v místě, kde používáte software.
<br/>
<br/>
<span style="font-weight: bold;">9.&nbsp;&nbsp; &nbsp;ROBOTI, UMĚLÁ INTELIGENCE A JINÉ SYSTÉMY:</span>
<br/> Je přísně zakázáno používat jakýkoli automatizovaný software nebo počítačový systém při hře na na [Metadata: HTMLEncode (/Metadata/Settings.Operator_DisplayName)], včetně působení zasílání informací z počítače do jiného počítače, kde je takový software nebo systém aktivní. Poker-roboty, nebo jakýkoliv software navržený tak, aby automaticky hrál na pokerových stránkách není dovolen. Kdykoliv, když hrajete na [Metadata: HTMLEncode (/Metadata/Settings.Operator_DisplayName)], Software může skenovat váš počítač pro jakoukoli činnost takového typu. Rovněž je zakázáno používání jakéhokoli softwaru v průběhu hry, který je navržen tak, aby sledoval a zobrazoval akce ostatních hráčů na webu, nebo jakéhokoli systému nebo služby, které převádí finanční prostředky hráči nebo od hráče [Metadata: HTMLEncode (/ Metadata / Settings.Operator_DisplayName)] na svůj účet v jakémkoliv jiném webu nebo záměrné "přehazování" čipů mezi účty, na síti Cake Poker. Využití těchto metod bude mít za následek uzavření Vašeho účtu a vase prostředky budou podléhat konfiskaci. [Metadata: HTMLEncode (/Metadata/Settings.Operator_DisplayName)] si vyhrazuje právo zveřejnit informaci o takovém zdokumentovaném zneužívání včetně vašich osobních údajů.
<br/>
<br/>
<span style="font-weight: bold;">10.&nbsp;&nbsp; &nbsp;ŽÁDNÍ ZAMĚSTNANCI SPOLEČNOSTI:</span>
<br/> Jste-li úředník, ředitel, zaměstnanec, poradce nebo zástupce společnosti nebo jedné z jejích společností ve skupině, nebo dodavateli či prodejci, nemůžete se registrovat [Metadata: HTMLEncode (/Metadata/Settings.Operator_DisplayName )], nebo se přímo nebo nepřímo podílet na některé z [Metadata: HTMLEncode (/Metadata/Settings.Operator_DisplayName)] herních služeb (dále "neoprávněná osoba"), pokud to tak konáte na základě písemného souhlasu [metadat: HTMLEncode (/Metadata/Settings.Operator_DisplayName)], a je taková účast je součástí vašeho pracovního poměru a / nebo součástí propagace [Metadata: HTMLEncode (/Metadata/Settings.Operator_DisplayName)]. Stejně tak, příbuzní nepovolaných osob se nemohou registrovat [Metadata: HTMLEncode (/Metadata/Settings.Operator_DisplayName)], nebo se přímo nebo nepřímo podílet na některé ze služeb. Pro tyto účely se zavádí pojem " příbuzný " (ale není limitován jen na) některého z manželů, partnerů, rodiče, děti a sourozence.
<br/>
<br/>
<span style="font-weight: bold;">11.&nbsp;&nbsp; &nbsp;HERNÍ PENÍZE:</span>
<br/> Herní peníze nejsou skutečné (bona fide), a jsou uchovávány odděleně od skutečných peněz. Herní peníze nepředstavují vůbec žádnou hodnotu ve skutečném světě. Herní peníze mohou být použity pouze pro hraní v rámci herních tabulek, a nemohou být proplaceny, nebo jakýmkoli jiným způsobem přeměněny nebo převedeny mezi [Metadata: HTMLEncode (/Metadata/Settings.Operator_DisplayName)] a Vámi, nebo jakýmkoli jiným osobám či právnickým osobám.
<br/>
<br/>
<span style="font-weight: bold;">12.&nbsp;&nbsp; &nbsp;SKUTEČNÉ PENÍZE:</span>
<br/> Chcete-li hrát s reálnými penězi, jste povinni vložit skutečné peníze na svůj účet pomocí metod, které vám poskytl [Metadata: HTMLEncode (/Metadata/Settings.Operator_DisplayName)]. Minimální i maximální limity se vztahují na skutečné peníze vkladů. Všechny skutečné peníze budou vyplaceny, sledovány a vedeny v amerických dolarech, a nebudou generovat žádný zisk. Veškeré poplatky vybírané poskytovateli plateb, jsou na vaší zodpovědnost. Použití kreditní karty k financování vašeho [Metadata: HTMLEncode (/Metadata/Settings.Operator_DisplayName)] účtu může být považována za předplatbu bankou, která vydává své kreditní karty. Veškeré úroky a nebo poplatky spojené s předplatbou jsou na vaší zodpovědnost. Prosím, udržujte takovou rychlost, při které budete hrát přiměřeně rychle. Pokud hrajete na více než na jednom stole a [Metadata: HTMLEncode (/Metadata/Settings.Operator_DisplayName)] přijímá příliš mnoho stížností na vaší rychlost hry, [Metadata: HTMLEncode (/Metadata/Settings.Operator_DisplayName)] může omezit počet tabulek, s nimiž jste oprávněni hrát. [Metadata: HTMLEncode (/Metadata/Settings.Operator_DisplayName)] nenese odpovědnost za případné škody vzniklé v důsledku náhodné sázky pod Vaším jménem v průběhu hry, nebo při hraní na více stolech z důvodu přepínání mezi několika obrazovek. Ujistěte se, že hrajete na úrovni odpovídající vaším dovednostem při hře na [Metadata: HTMLEncode (/Metadata/Settings.Operator_DisplayName)].
<br/>
<br/>
<span style="font-weight: bold;">13.&nbsp;&nbsp; &nbsp;VÝBĚRY PENĚZ:</span>
<br/> V pokladní části software budete moci sledovat svůj zůstatek na účtu, který odpovídá částce skutečných peněz, kterou máte k dispozici, plus nebo minus veškeré kumulované výhry nebo prohry z hraní některých z her, po odečtení částky dříve vyplacených, propadlých nebo uvolněných prostředků [Metadata: HTMLEncode (/Metadata/Settings.Operator_DisplayName)]. Všechny vyplacené částky se vztahují transakční limity a poplatky za zpracování [Metadata: HTMLEncode (/Metadata/Settings.Operator_DisplayName)]. Limity a poplatky se mohou měnit čas od času na [Metadata: HTMLEncode (/Metadata/Settings.Operator_DisplayName)], dle vlastního uvážení nebo v případě vámi definovaných limitů. Peněžní výplaty se provádějí pouze prostřednictvím metod, které jsou dostupné [Metadata: HTMLEncode (/Metadata/Settings.Operator_DisplayName)] v pokladní sekci softwaru a budou vyplaceny stejným způsobem jako byly vloženy.
<br/>
<br/>
<br/>
<span style="font-weight: bold;">14.&nbsp;&nbsp; &nbsp;BEZPEČNOSTNÍ PROVĚRKY, REVIZE A VYDÁNÍ:</span>
<br/> [Metadata: HTMLEncode (/Metadata/Settings.Operator_DisplayName)] si vyhrazuje právo ověřit si vaší identitu a věrnost informací, které jste nám předali, různými bezpečnostními a identifikačními kontrolami. Pokud se vám nepodaří dodat požadovaná data, nebo odmítnoutnete na vyžádání vyhovět a podepsat žádost z [Metadata: HTMLEncode (/Metadata/Settings.Operator_DisplayName)], [Metadata: HTMLEncode (/Metadata/Settings.Operator_DisplayName)] si vyhrazuje právo zrušit váš účet.
<br/>
<br/>
<strong> 15 </ strong> & nbsp; & nbsp; & nbsp; Pokud není na účtu hráče zaznamenána po dobu 30 měsíců žádná transakce, zůstatek na tomto účtu musí být poukázán zoět hráči, nebo v případě, že hráč nemůže být uspokojivě nalezen, prostředky budou poukázány na LGA.
<br/>
<span style="font-weight: bold;">
<br/>16.&nbsp;&nbsp; &nbsp;[Metadata:htmlencode(/Metadata/Settings.Operator_DisplayName)] DOPORUČ KAMARÁDA:</span>
<br/> Přijetím této smlouvy, souhlasíte s tím, aby [Metadata: HTMLEncode (/Metadata/Settings.Operator_DisplayName)] vás odměnil bonusy v reálných penězích z ovartu vytvořeného jinými hráči, kterým jsi pomáhal při otevírání účtu se skutečnými penězi. Tato situace obvykle nastane, pokud jste přeal svou e-mailovou adresu ostatním hráčům a přiměl jste je, aby se na vás odkázali při vytváření účtu. [Metadata: HTMLEncode (/Metadata/Settings.Operator_DisplayName)] může čas od času nabízet další propagační akce nebo iniciativy, které jsou navrženy proto, aby jste mohli být odměňováni za přivedení nového hráče se skutečnými penězi[Metadata: HTMLEncode (/Metadata/Settings.Operator_DisplayName) ]. [Metadata: HTMLEncode (/Metadata/Settings.Operator_DisplayName)] není odpovědný za neschopnost uvedeného hráče správně doložit jeho / její e-mailovou adresu. [Metadata: HTMLEncode (/Metadata/Settings.Operator_DisplayName)] si vyhrazuje právo na změnu pravidel, úrovně a limity programu Doporuč kamaráda na základě vlastního uvážení.
<br/>
<br/>
<strong>17.</strong>&nbsp;&nbsp; &nbsp;
<br/> 1. & nbsp; & nbsp; & Nbsp; Platba: Váš účet bude připsán bonus z programu Doporuč kamaráda [Metadata: HTMLEncode (/Metadata/Settings.Operator_DisplayName)] do sedmi dnů od skončení každého kalendářního měsíce.
<br/> 2. & nbsp; & nbsp; & Nbsp; Uvolnění Úrovně a přidružené bonusy: Pravidla, jimiž se řídí, jak odemknout úrovní a příslušné odměny se nacházejí na [Metadata: HTMLEncode (/Metadata/Settings.Operator_DisplayName)] softwaru (Klikněte na odměny - & gt; viz Doporuč kamaráda). Bonusy jsou založeny na bodech častého hráče (Frequent Player Points) vytvořených zmíněným hráčem. Nesplnění požadavků na zisk bodů častého hráče v daných úrovních, nehledě na důvody, bude mít za následek, že další úrovně zůstávají uzamčené či nebvyužité. 
<br/> 3. & nbsp; & nbsp; & Nbsp; Nedovolené reklamní praktiky: Nedovolené reklamní praktiky: [Metadata: HTMLEncode (/Metadata/Settings.Operator_DisplayName)] se vám odmění za šíření informací ostatním o našich službách v oblasti her. Nicméně, sledujeme metody používané k podpoře [Metadata: HTMLEncode (/Metadata/Settings.Operator_DisplayName)], a pokud bylo zjištěno, že jste:
<br/> 4. & nbsp; & nbsp; & nbsp;
<br/>. & nbsp; & nbsp; & nbsp; posílali hromadné e-maily a nevyžádaná e-mailové, 
<br/> b. & nbsp; & nbsp; & nbsp; svévolně a bezostyšně ignorovali pravidla webových stránek třetí strany zveřejněňováním pozvánek k registraci, a / nebo
<br/> c. & nbsp; & nbsp; & nbsp; pomocí reklamních sdělení s hrubě zavádějícími tvrzeními o propagačních odměnách
<br/> Může být vase účast v [Metadata: HTMLEncode (/Metadata/Settings.Operator_DisplayName)] program Doporuč kamaráda pozastavena nebo ukončena.<br/>
<br/>
<br/>
<strong>18.</strong>
<br/> 4. & nbsp; & nbsp; & nbsp; Ukončení účasto v programu Doporuč kamaráda: výše uvedené nevhodné reklamními praktiky mohou vést k ukončení vaší účasti v [Metadata: HTMLEncode (/Metadata/Settings.Operator_DisplayName)] programu Doporuč kamaráda. To zahrnuje propadnutí vašich současných zisků z programu, propadnutí jakékoli budoucího zisku z programu Doporuč kamaráda a ztrátou schopnosti získávat přátele pro tento program.
<br/>
<br/>
<span style="font-weight: bold;">19.&nbsp;&nbsp;&nbsp;&nbsp;ZLATÁ KARTA:</span>
<br/> Přijetím této smlouvy, souhlasíte s tím, aby [Metadata: HTMLEncode (/Metadata/Settings.Operator_DisplayName)] vás odměňoval Zlatou kartou/Zlatými kartami pro vase hry se skutečnými penězi. V případě, že cena je vyhlašován na Zlatou kartu, kterou máte v té době k dispozici, je Vaší povinností vykoupit Zlatou kartu před zveřejněným časem vypršení. Žádné Zlaté karty nebudou moci být vykoupeny za tuto cenu, jakmile čas pro danou cenu vypršel. Vaše Zlatá karta nevyprší a zůstane na vašem účtu, dokud účet není zrušený (viz kapitola 15).
<br/>
<br/>
<span style="font-weight: bold;">20.&nbsp;&nbsp;&nbsp;&nbsp;ZLATÉ ŽETONY:</span>
<br/> Přijetím této smlouvy souhlasíte s tím, aby [Metadata: HTMLEncode (/Metadata/Settings.Operator_DisplayName)] vás odměňoval Zlatým žetonem na základě pravidel stanovených na [Metadata: HTMLEncode (/Metadata/Settings.Operator_DisplayName )] webové stránka) . Vaše Zlatá žetony nevyprší a zůstaneouna vašem účtu, dokud účet není zrušený (viz kapitola 13).
<br/>
<br/>
<span style="font-weight: bold;">21.&nbsp;&nbsp;&nbsp;VEDENÍ ÚČTŮ:</span>
<br/>Po dobu existence vašeho účtu, mohou existovat okolnosti, které vyžadují změny údajů v účtu.<br/>
<br/>
<strong>22.

<br/> </ strong> 1. & nbsp; & nbsp; & Nbsp; Dědictví: V případě Vaší smrti nebo trvalé pracovní neschopnosti, [Metadata: HTMLEncode (/Metadata/Settings.Operator_DisplayName)] vyžaduje kopii úmrtního listu nebo prohlášení registrovaného lékaře a dalších dokladů týkajících se správy nebo opatrovnictví Vašeho majetku jako důkaz, že Váš dědic nebo opatrovník mají na váš majetek (společně jen "oprávněné osoby") nárok. V tomto případě jakékoliv z vašich příjmů práv a / nebo majetek na vašem účtu mohou přecházet na vaši dědice. Vaše dědici či opatrovníci musí podat písemnou žádost spolu s potřebnou dokumentaci, včetně potvrzení o úmrtí nebo prohlášení registrovaného lékaře ke zvážení [Metadata: HTMLEncode (/Metadata/Settings.Operator_DisplayName)]. Schválení této žádosti nebude bezdůvodně odepřeno. Převody budou schváleny pouze v případě, že příjemci souhlasí s tím, aby převzali váš účet s povinnosti a závazky, jak je uvedeno v těchto podmínkách & amp; Podmínky. Nemůže-li příjemce vlastnit účet, bude příjemce oprávněn převést hotovost naúčet třetí osobě, která je oprávněna vlastnit [Metadata: HTMLEncode (/Metadata/Settings.Operator_DisplayName)] účet.
<br/> 2. & nbsp; & nbsp; & nbsp; Pozastavení účtu: [Metadata: HTMLEncode (/Metadata/Settings.Operator_DisplayName)] si vyhrazuje právo kontrolovatčinnost vašeho účtu a upozornit vás, pokud [Metadata: HTMLEncode (/Metadata/Settings.Operator_DisplayName)] se domnívá, že můžete mít problémy s hazardními hrami. Nicméně, [Metadata: HTMLEncode (/Metadata/Settings.Operator_DisplayName)] neposkytuje žádné záruky ohledně vlastní schopnosti identifikovat tento problém a pomoci vám s problémy hazardu. Sami můžete požádat o pozastavení přístupu na váš účet pomocí tlačítka [Metadata: HTMLEncode (/Metadata/Settings.Operator_DisplayName)] z různých důvodů, můžete tak učinit kdykoliv na základě žádosti zaslané na <a href = "mailto: [metadat: HTMLEncode (/Metadata/Settings.Email_SupportAddress)] "target =" _ blank "> [Metadata: HTMLEncode (/Metadata/Settings.Email_SupportAddress)] </a>
<br/> 3. & nbsp; & nbsp; & Nbsp; Pozastavení a zánik účtu: [Metadata: HTMLEncode (/Metadata/Settings.Operator_DisplayName)] si vyhrazuje právo ukončit váš účet kdykoliv, porušíte-li některé z těchto podmínek poskytování služeb; nebo pokud poskytnete nepravdivé nebo zavádějící informace [Metadata: HTMLEncode (/Metadata/Settings.Operator_DisplayName)]; nebo pokud se podílíte se na podvodné, nevhodné nebo urážlivé činnosti vůči [Metadata: HTMLEncode (/Metadata/Settings.Operator_DisplayName)] nebo jakémukoli [Metadata: HTMLEncode (/Metadata/Settings.Operator_DisplayName)] uživateli; nebo se podílíte na činnostech, které mohou být považovány za činnosti v rozporu s uznávanými normami poctivého jednání  či v rozporu s platnými právními předpisy ve Vaší jurisdikci a / nebo které jsou v rozporu se zájmy [Metadata: HTMLEncode (/Metadata/Settings.Operator_DisplayName)], nebo pokud způsobují újmu na [Metadata: HTMLEncode (/Metadata/Settings.Operator_DisplayName)] pověsti. Toto ukončení musí být učiněno na [Metadata: HTMLEncode (/Metadata/Settings.Operator_DisplayName)] dle vlastního uvážení. Opatření mohou být přijata [Metadata: HTMLEncode (/Metadata/Settings.Operator_DisplayName)] v případě, že vaše se tak chováte, může zahrnovat, ale není omezeno na,  varování, dočasné pozastavení [metadat: HTMLEncode (/Metadata/Settings.Operator_DisplayName)] služby, a dočasné pozastavení vašeho [metadat: HTMLEncode (/Metadata/Settings.Operator_DisplayName)] účtu.
<br/>
<br/> Ukončení vašeho [Metadata: HTMLEncode (/Metadata/Settings.Operator_DisplayName)] účtu bude zvažována pouze v případě nejzávažnějších porušení, nebo v důsledku několikanásobného porušení pravidel a tam, kde je to možné, až po opakované komunikace s vámi. V případě ukončení vašeho [Metadata: HTMLEncode (/Metadata/Settings.Operator_DisplayName)] účet [Metadata: HTMLEncode (/Metadata/Settings.Operator_DisplayName)] je společnost oprávněna přijmout taková opatření, která považuje za vhodná, včetně okamžitého blokování přístupu k [metadat: HTMLEncode (/Metadata/Settings.Operator_DisplayName)] herním službám, zajištění veškerých prostředků z vašeho účtu, zveřejnění těchto informace (včetně vaší totožnosti), aby banky, společnosti vydávající kreditní karty a / nebo jakékoli fyzické nebo právnické osoby, které má zákonné právo k těmto informacím, a / nebo právní kroky proti vám. V případě ukončení vašeho účtu, souhlasíte s tím:
<br/>. & nbsp; & nbsp; & nbsp; & nbsp; & nbsp; & nbsp; Vaše právo na reprezentaci [Metadata: HTMLEncode (/Metadata/Settings.Operator_DisplayName)] se jakýmkoliv způsobem okamžitě odvolává;
<br/> b. & nbsp; & nbsp; & nbsp; & nbsp; & nbsp; & nbsp; Vaše právo používat [Metadata: HTMLEncode (/Metadata/Settings.Operator_DisplayName)] služby, svůj uživatelský účet a heslo je okamžitě zrušeno;
<br/> c. & nbsp; & nbsp; & nbsp; & nbsp; & nbsp; & nbsp; Musíte zničit / odstranit všechny kopie Softwaru.
<br/> d. & nbsp; & nbsp; & nbsp; & nbsp; & nbsp; & nbsp; Vaše právo na jakékoliv současné nebo budoucí nároky vznikající z [Metadata: HTMLEncode (/Metadata/Settings.Operator_DisplayName)] nebo vaše užívání [Metadata: HTMLEncode (/Metadata/Settings.Operator_DisplayName)] služeb, se ruší k datu ukončení; a
<br/> e. & nbsp; & nbsp; & nbsp; & nbsp; & nbsp; & nbsp; Všechna ostatní práva v rámci těchto podmínek se ukončí.
<br/> 4. & nbsp; & nbsp; & nbsp; Omezení na chatu
<br/> - & nbsp; & nbsp; & nbsp; & nbsp; nesmíte mluvit o tahu v jeho průběhu.
<br/> - & nbsp; & nbsp; & nbsp; & nbsp; Neměli byste v chatu radit jinému hráči během hry, nebo nutit hráče k určitému postupu.
<br/> - & nbsp; & nbsp; & nbsp; & nbsp; nesmíte mluvit o složení karet, které jste měli v ruce během hry, nebo o aktuálních kartách, které jsou ve hře. 
<br/> - & nbsp; & nbsp; & nbsp; & nbsp; byste měli mluvit na chatu pouze v anglickém jazyce a konkrétní jazyk uvedeném v tabulce, jak může být určeno [Metadata: HTMLEncode (/Metadata/Settings.Operator_DisplayName)] dle jeho uvážení.
<br/> - & nbsp; & nbsp; & nbsp; & nbsp; byste neměli používat hrubý, urážlivý nebo vyhrožujícící jazyk.
<br/> Výše uvedené akce nejsou podporovány, protože vykazují špatnou etiketu hráčů a mohou mít za následek pozastavení chatu nebo v závažných a opakujících se případech porušování platí úplný zákaz chatu nebo uzavření účtu. & nbsp; & nbsp; & nbsp; & nbsp;
<br/> 5. & nbsp; & nbsp; & nbsp; Další porušení jakýchkoli částí těchto podmínek může také vést k propadnutí jakýchkoli nebo všech stávajících peněz, zůstatků, ceny nebo výher z hazardních her a jakýchkoli nároků, které byste jinak měli nebo které by vyplývaly z vašeho [metadat: HTMLEncode (/Metadata/Settings.Operator_DisplayName)] účtu nebo užívání [Metadata: HTMLEncode (/Metadata/Settings.Operator_DisplayName)] služeb. [Metadata: HTMLEncode (/Metadata/Settings.Operator_DisplayName)] rovněž vyhrazuje právo na náhradu za jakoukoli ztrátu vyplývající z nedodržení jakýchkoli závazků obsažených v těchto podmínkách. [Metadata: HTMLEncode (/Metadata/Settings.Operator_DisplayName)] si vyhrazuje právo zrušit a zavřít [metadat: HTMLEncode (/Metadata/Settings.Operator_DisplayName)] účet z jakéhokoli ospravedlnitelného důvodu kdykoliv a bez předchozího upozornění.
<br/>
<br/>
<span style="font-weight: bold;">23.&nbsp;&nbsp; &nbsp; PROZRAZENÍ TŘETÍM OSOBÁM:</span>
<br/> Souhlasíte s tím, že budete váš účet a související informace držet v tajnosti, a aby je nikdo jiný je nebude používat. Pokud úmyslně nebo neúmyslně, přímo či nepřímo, zveřejníte e-mail a / nebo heslo jiné osobě, a taková třetí osoba se účastní [Metadata: HTMLEncode (/Metadata/Settings.Operator_DisplayName)] služeb pomocí vašeho e -mail a hesla, taková účast bude neplatná, a nedostanete zpět žádné prohrané prostředky na [Metadata: HTMLEncode (/Metadata/Settings.Operator_DisplayName)], bez ohledu na to, zda třetí osoba měla váš souhlas, nebo ne. Společnost není povinna uchovávat e-maily nebo hesla, v případě, že je ztratíte nebo zapomenete a nebo nejste schopni vstoupit na [Metadata: HTMLEncode (/Metadata/Settings.Operator_DisplayName)] z jiného důvodu, než z chyby společnosti.
<br/>
<br/>
<span style="font-weight: bold;">24.&nbsp;&nbsp; &nbsp; ODŠKODNĚNÍ:</span>
<br/> Souhlasíte, že odškodníte, budete chránit a bránit [metadat: HTMLEncode (/Metadata/Settings.Operator_DisplayName)], a její mateřské společnosti, pobočky, ředitele, akcionáře, zaměstnance, agenty, licenční partnery od  Veškerých nároků, ztrát, závazků, škod, nákladů nebo výdajů (včetně přiměřených poplatků za právní zastoupení), které vznikají jakoukoli třetí stranou v souvislosti jakýmkoli způsobem s (a) Vaším využíváním [Metadata: HTMLEncode (/ Metadata / Settings.Operator_DisplayName)] služeb, nebo jakýkoliv jiným produktem, službou nebo nabídkou, které vám nabídne [Metadata: HTMLEncode (/Metadata/Settings.Operator_DisplayName)]; (B) jakýkoli nárok z porušení třetích stran práv na ochranu duševního vlastnictví; (C) nahrávání, vysílání, posílání e-mailů, reprodukci, přenos nebo jinou distribuci jakéhokoliv obsahu nebo jiných materiálů; nebo (d) porušením některých z těchto podmínek, ať vámi či všemi uživateli vašeho účtu na [Metadata: HTMLEncode (/Metadata/Settings.Operator_DisplayName)]. [Metadata: HTMLEncode (/Metadata/Settings.Operator_DisplayName)] si vyhrazuje právo převzít výhradní obhajobu a kontrolu jakékoliv záležitosti podléhající vašemu odškodnění, kteráváš však nesmí sprostit vašich povinností.
<br/>
<br/>
<span style="font-weight: bold;">25.&nbsp;&nbsp; &nbsp;URÁŽLIVÝ A SPROSTÝ JAZYK:</span>
<br/> Urážlivý a sprostý jazyk nebude tolerován v [Metadata:htmlencode(/Metadata/Settings.Operator_DisplayName)] službách nebo vůči zaměstnancům [Metadata:htmlencode(/Metadata/Settings.Operator_DisplayName)]. Jakékoliv porušení tohoto pravidla bude mít za následek pozastavení herních práv nebo takové jiné činnosti, které může být požadováno [Metadata: HTMLEncode (/Metadata/Settings.Operator_DisplayName)] k zajištění dodržování podmínek. Je zakázáno používat nevhodný nebo urážlivý jazyka v souvislosti s vaším uživatelským jménem a / nebo hráčským ID, který zahrnuje, ale není omezen pouze na vulgarity, sexismus nebo rasistický jazyk. [Metadata: HTMLEncode (/Metadata/Settings.Operator_DisplayName)] si vyhrazuje právo provádět změny libovolných jmen uživatelů nebo hráčského ID, která porušují tyto zásady, a podniknout veškeré kroky, které uzná za vhodné, až do zrušení účtu. Pokud si uživatel vytvořil účet s ofenzivním uživatelské jméno a / nebo hráčským ID nebo změnil své stávající uživatelské jméno / ID na útočné, může dojít 

