<p>Ahoj $FIRSTNAME$,</p>
<p>vaša poukážka v hodnote $VOUCHERAMOUNT$  bola spracovaná. Nižšie nájdete ďalšie údaje:</p>
<ul>
<li><strong>Číslo poukážky Ukash</strong>:$VOUCHERNUMBER$</li>
<li><strong>Hodnota poukážky</strong>:$VOUCHERAMOUNT$</li>
<li><strong>Platnosť poukážky</strong>:$VOUCHEREXPIRYDATE$</li>
</ul>
<p>Ak máte nejaké otázky, obráťte sa prosím na <a href="mailto:[Metadata:htmlencode(/Metadata/Settings.Email_SupportAddress)]">[Metadata:htmlencode(/Metadata/Settings.Email_SupportAddress)]</a>.</p><p>S pozdravom,<br /> [Metadata:htmlencode(/Metadata/Settings.Operator_DisplayName)] tím</p>
