EntroPay je predplatná, virtuálna VISA karta ktorá môže byť použitá kdekoľvek kde je akceptovaná VISA. Pridať prostriedky na vašu AstroPayCard môžete s vašou platobou katrou alebo bankovým prevodom.<br /><br />
Registovanie EntroPay VISA zaberie iba chvíľu a hneď ju môžete používať!

<a href="https://secure2.entropay.com/processes/upaffiliatelanding/unprot/affiliatewelcome.do?referrerID={0}" target="_blank">Kliknite sem</a> pre otvorenie vášho EntroPay účtu.
