<p>Vážený/á $USERNAME$,<br /> </p>
<br />
tento e-mail potvrdzuje, že na vašom účte bolo aktivované sebavylúčenie.
<br /><br />
Už sa nemôžete prihlásiť na účet.<br /><br />
Ak máte nejaké otázky, obráťte sa prosím na <a href="mailto:[Metadata:htmlencode(/Metadata/Settings.Email_SupportAddress)]">[Metadata:htmlencode(/Metadata/Settings.Email_SupportAddress)]</a><p>&#160;</p><p><br />S pozdravom</p><p>[Metadata:htmlencode(/Metadata/Settings.Operator_DisplayName)] Oddelenie zákazníckej podpory</p>

