Tento e-mail sa posiela automaticky, prosím neodpovedajte naň.  
<hr/>
<p>Vážený/á $FIRSTNAME$</p>
<p>váš účet bol zablokovaný z dôvodu viacerých neúspešných pokusov o prihlásenie a bude automaticky odblokovaný za 15 minút.</p>
<p>Ak ste zabudli svoje heslo, kliknite prosím na odkaz &quot;Zabudnuté heslo?&quot; na webovej stránke.</p>
<p>Ak máte nejaké otázky, obráťte sa prosím na <a href="mailto:[Metadata:htmlencode(/Metadata/Settings.Email_SupportAddress)]">[Metadata:htmlencode(/Metadata/Settings.Email_SupportAddress)]</a><p>&#160;</p><p><br />S pozdravom</p><p>[Metadata:htmlencode(/Metadata/Settings.Operator_DisplayName)] Oddelenie zákazníckej podpory</p>
