Vážený/á $USERNAME$, <br />
<br />
týmto vám oznamujeme, že doba sebavylúčenia na vašom účte uplynula a vy se môžete znovu prihlásiť na svoj účet.<br />
<br />Ak máte nejaké otázky, obráťte sa prosím na <a href="mailto:[Metadata:htmlencode(/Metadata/Settings.Email_SupportAddress)]">[Metadata:htmlencode(/Metadata/Settings.Email_SupportAddress)]</a><p>&#160;</p><p><br />S pozdravom</p><p>[Metadata:htmlencode(/Metadata/Settings.Operator_DisplayName)] Oddelenie zákazníckej podpory</p>
