<p>Dobrý deň $FIRSTNAME$,</p>
<p>Váš vklad bol úspešný.</p>
<p><span style="font-size: medium;"><strong style="color: #ff3366;"> Prosím kliknite "Obnoviť" (nie vo vašom prehliadači) ale na našej stránke aby sa vám obnovil stav účtu </strong></span></p>
<p>Ak máte nejaké otázky neváhajte nás kontaktovať <a href="mailto:[Metadata:htmlencode(/Metadata/Settings.Email_SupportAddress)]">[Metadata:htmlencode(/Metadata/Settings.Email_SupportAddress)]</a>.</p>
<p>S pozdravom,<br /> [Metadata:htmlencode(/Metadata/Settings.Operator_DisplayName)] tím</p>
