<ol> </ol>
<p>Tyto zásady ochrany osobních údajů se mohou měnit, prosím kontrolujte je pravidelně. Vyhrazujeme si právo změnit nebo upravit tyto zásady kdykoliv, v reakci na změny v příslušné oblasti práv a ochrany údajů a zákonů na ochranu soukromí. V případě, že se nařízení změní, budeme Vás co nejdříve informovat. </p>
<ol start="1">
<ol>
<li><strong>ÚVOD:</strong>
<p>1.1.&nbsp;&nbsp; &nbsp; Používáním a / nebo navštívením jakékoliv části webových stránek&nbsp; [Metadata:htmlencode(/Metadata/Settings.Operator_DisplayName)] (dále jen „Webové stránky“); nebo založením účtu na webových stránkách souhlasíte s následujícími ustanoveními: 
1.1.1.&nbsp;&nbsp; &nbsp; Všeobecná obchodní Pravidla a Podmínky, dostupné na této stránce;<br /> 1.1.2.&nbsp;&nbsp; &nbsp; Zásady ochrany osobních údajů, <br /> 1.1.3.&nbsp;&nbsp; &nbsp; pravidla všech her,<br /> 1.1.4.&nbsp;&nbsp; &nbsp; veškeré podmínky &nbsp; akcí, bonusů a speciálních nabídek, které se někdy mohou být nalezeny na internetových stránkách. <br /> 1.2.&nbsp;&nbsp; &nbsp; Všechny výše uvedené pravidla a podmínky budou nadále souhrnně nazývány jen jako „Podmínky“. <br /> 1.3.&nbsp;&nbsp; &nbsp; Přečtěte si Podmínky pozorně před jejich schválením. Pokud nesouhlasíte a nechcete být vázáni Podmínkami, neotevírejte si účet či nadále nepoužívejte Webové stránky. Dalším používání Webových stránek vyjadřujete svůj souhlas s podmínkami. <br /> 1.4.&nbsp;&nbsp; &nbsp; Tyto podmínky vstoupí v platnost dne 9. června 2010.</p>
<ol start="2">
<li><b>STRANY</b> </li>
</ol>
<p>2.1.&nbsp;&nbsp; &nbsp; Termíny použité v Podmínkách, jako například „my“, „naše“, nebo „společnost“, jsou odkazy na stranu, s nimiž uzavíráte smluvní vztah, jak je uvedeno výše.</p>
<ol start="3"> 
<li><b>ZMĚNY V PODMÍNKÁCH </b> </li>
 </ol>
<p>3.1.&nbsp;&nbsp; &nbsp; Společnost může změnit Podmínky z celé řadu důvodů, včetně obchodních důvodů, dále pro sladění znění s novými zákony a předpisy, nebo z důvodů větší podpory zákazníků. Aktuální verze Podmínek je k nalezení zde společně s datem, kdy vešly v platnost.
 <br /> 3.2.&nbsp;&nbsp; &nbsp; V případě provedení změn Podmínek vás o konkrétních změnách budeme informovat pomocí emailu či umístěním oznámení na Webových stránkách. </p>
<ol start="4">
 <li><b> ZALOŽENÍ ÚČTU </b> </li>
</ol>
<p>4.1.&nbsp;&nbsp; &nbsp; K tomu, abyste mohli začít sázet prostřednictvím Webových stránek, musíte si založit účet na webových stránkách („Váš Účet“).<br /> 4.2.&nbsp;&nbsp; &nbsp; Z různých právních a obchodních důvodů nedovolujeme otevřít či používat účty osobám sídlícím v určitých oblastech, včetně Spojených států amerických. Žijete-li v těchto oblastech, nemůžete si založit účet či používat Webové stránky.<br /> 4.3.&nbsp;&nbsp; &nbsp; Aby bylo možné otevřít Váš účet a mohli jste začít používat Webové stránky, obraťte se na zákaznickou podporu, nebo klikněte sem a postupujte podle pokynů na obrazovce.
 <br /> 4.4.&nbsp;&nbsp; &nbsp; Při otevření účtu budete požádáni o poskytnutí osobních údajů, včetně vašeho jména, data narození, a aktuálních kontaktních údajů, včetně adresy, telefonního čísla a e-mailové adresy („Vaše kontaktní údaje“). <br /> 4.5.&nbsp;&nbsp; &nbsp; Využíváním služeb poskytovaných na Webových stránkách berete na vědomí a přijímáte fakt, že můžete vyhrát i prohrát peníze.<br /> 4.6.&nbsp;&nbsp; &nbsp; Váš účet musí být registrován pod vlastním správným jménem. Pro účel sázení si můžete otevřít pouze jeden účet. Jakékoliv jiné účty, které otevřete pro účel využívání námi poskytovaných služeb, budou považovány za „duplicitní“ účty. Jakékoliv duplicitní účty mohou být uzavřeny s okamžitou platností z naší strany a: <br /> 4.6.1.&nbsp;&nbsp; &nbsp; Všechny transakce provedené z duplicitního účtu bude neplatné;
<br /> 4.6.2.&nbsp;&nbsp; &nbsp; Všechny sázky nebo vklady, provedené pomocí duplicitního účtu budou vráceny; <br /> 4.6.3.&nbsp;&nbsp; &nbsp; Všechny vrácené peníze, výhry nebo bonusy, které jste získali nebo nabyli v průběhu doby, kdy byl duplicitní účet otevřen, Vám propadají a mohou být námi požadovány zpět. Na požádání vrátíte všechny takovéto prostředky, získané z duplicitního účtu. <br /> 4.7.&nbsp;&nbsp; &nbsp; Chcete-li otevřít další účet, můžete se obrátit na správce na<a href="mailto:support@exclusivebet.com" target="_blank">support@exclusivebet.com</a>. Pokud si otevřete nový účet, starý účet bude uzavřen.  <br /> 4.8.&nbsp;&nbsp; &nbsp; Musíte udržovat svůj účet a data na něm uvedená aktuální.</p>
<ol start="5">
<li><b> OVĚŘENÍ VAŠÍ IDENTITY; PRANÍ ŠPINAVÝCH PENĚZ </b> </li>
</ol>
<p>5.1.&nbsp;&nbsp; &nbsp; Tímto se zaručujete, že: <br />5.1.1.&nbsp;&nbsp; &nbsp; Nejste mladší:<br />5.1.1.1.&nbsp;&nbsp; &nbsp; 18 (osmnácti) let; nebo<br />5.1.1.2.&nbsp;&nbsp; &nbsp; než je jakýkoli zákonný věk, požadovaný zákonem a místní jurisdikcí pro veškeré hazardní hry nebo herní činnosti (dále jen „zletilost“);<br />5.1.2.&nbsp;&nbsp; &nbsp; Údaje poskytnuté při otevření účtu jsou správné; <br />5.1.3.&nbsp;&nbsp; &nbsp; . Jste právoplatným vlastníkem peněz na vašem účtu. <br />5.2.&nbsp;&nbsp; &nbsp; Souhlasem s Podmínkami nás povolujete provádět kontroly (dále „Kontroly“) vaší totožnosti a kontaktních údajů pro potřebu jak naší, či dle požadavků třetích stran (včetně regulačních orgánů). <br />5.3.&nbsp;&nbsp; &nbsp; V průběhu provádění kontrol můžeme omezit čerpání finančních prostředků z vašeho účtu.  <br />5.4.&nbsp;&nbsp; &nbsp; Za určitých okolností vás budeme kontaktovat a požádat o poskytnutí dalších informací pro úspěšné dokončení kontroly. Pokud nám neposkytnete nebo nemůže poskytnout takové informace, vyhrazujeme si právo pozastavit Váš účet, dokud nám neposkytnete požadované informace, případně můžeme trvale uzavřít váš účet. Pokaždé když budete chtít provést výběr peněžních prostředků ve výši dva tisíce tři sta eur (2300 EUR) nebo více, budete muset prokázat svou totožnost. <br />5.5.&nbsp;&nbsp; &nbsp; Pokud se nám nepodaří prokázat, že jste plnoletí, můžeme pozastavit Váš účet. Pokud se prokáže, že jste nedosáhli tohoto věku v době, kdy jste se účastnili hraní či jste prováděli transakce v nějaké z hazardních her, pak:<br />5.5.1.&nbsp;&nbsp; &nbsp; Váš účet bude uzavřen;<br />5.5.2.&nbsp;&nbsp; &nbsp; Všechny provedené transakce uzavřené vámi jako nezletilým hráčem budou neplatné, a všechny související prostředky, které jste vložil, Vám budou vráceny; <br />5.5.3.&nbsp;&nbsp; &nbsp; Jakékoli sázky, které jste uzavřel jako nezletilý, se vám vrátí;  <br />5.5.4.&nbsp;&nbsp; &nbsp; Jakékoliv výhry, které jste nabyl během této doby, Vám propadnou a vrátíte nám všechny prostředky, které byly vyplaceny z vašeho účtu. </p>
<ol start="6">
<li><b> UŽIVATELSKÉ JMÉNO, HESLO A INFORMACE O ZÁKAZNÍCÍCH </b> </li>
</ol>
<p>6.1.&nbsp;&nbsp; &nbsp; Po otevření Vašeho účtu, nesdělujte (ať už úmyslně nebo neúmyslně) vaše uživatelské jméno a heslo nikomu jinému. Pokud jste ztratili nebo zapomněli své údaje o účtu, můžete získat heslo kliknutím na odkaz &ldquo; Zapomenuté heslo&rdquo; , který najdete na přihlašovací stránce.</p>
 <ol start="7">
<li><b> VKLADY A VÝBĚRY Z ÚČTU </b> </li>
</ol>
<p>7.1.&nbsp;&nbsp; &nbsp; Pokud chcete sázet nebo hrát na Webových stránkách, musíte nejdříve vložit na svůj účet peníze, které pak můžete použít na sázky či hraní her.
  <br />7.2.&nbsp;&nbsp; &nbsp; Vklady a výběry do z účtu lze provést pomocí různých poskytovatelů plateb, kteří se však mohou čas od času měnit. V rámci jednotlivých poskytovatelů se postupy a podmínky mohou lišit. Neakceptujeme peníze v hotovosti.
  <br />7.3.&nbsp;&nbsp; &nbsp; Uložením peníz souhlasíte s tím, že nebudete platby zpětně rušit, či jakkoliv zpětně požadovat peníze vložené na váš účet, a souhlasíte s tím, že případné neproplacené vklady nám budete plně kompenzovat.
 <br />7.4.&nbsp;&nbsp; &nbsp; Váš účet není vedený jako účet v bance, a proto není pojištěný, ani není nijak zajištěný, ani jinak chráněný bankovního systémem pojištění. Krom toho, peníze uloženy u nás na Vašem účtu nebudou nijak zhodnocovány.
 <br />7.5.&nbsp;&nbsp; &nbsp; Můžeme kdykoliv odebrat část kladného zůstatku na vašem účtu, abychom pokryli splacení odpovídající částky, kterou nám dlužíte po vyrovnání účtů, vztahujících se k duplicitním účtům, tajným dohodám, klamání, podvodům, jakýmkoliv kriminálním aktivitám či chybám. 
 <br />7.6.&nbsp;&nbsp; &nbsp; Jste zodpovědní za nahlášení svých výher a ztrát pro účely odvedení daňové povinnosti v místě konané aktivity či pro účely jiných pověřených orgánů.
 <br />7.7.&nbsp;&nbsp; &nbsp; Kdykoliv můžete požádat o čerpání prostředků z účtu, za předpokladu, že:
 <br />7.7.1.&nbsp;&nbsp; &nbsp; všechny platby provedené z Vašeho účtu byly potvrzeny jako proběhlé a žádná nebyla stažena zpět, vymazána či jinak zrušena;
 <br />7.7.2.&nbsp;&nbsp; &nbsp; všechny Kontroly, uvedené výše v odstavci 5, byly dokončeny.
  <br />7.8.&nbsp;&nbsp; &nbsp; Pokud jsme schválili vyplacení peněz, musíte nám poskytnout dostatek informací o tom, jakým způsobem by měly být finanční prostředky vyplaceny. Pokusíme se vyhovět vaší žádosti, pokud jde o způsob platby a druh měny výplaty vašich prostředků. Vyhrazujeme si právo zvolit způsob platby a druh měny výplaty prostředků.
 <br />7.9.&nbsp;&nbsp; &nbsp; Vyhrazujeme si právo účtovat poplatek ve výši vlastních nákladů (včetně nákladů na vklad) v případě vyplacení finančních prostředků, které nebyly vloženy do hry
 <br /> 7.10.1. Hráči, kteří se zaregistrují na exbeteu.com mohou vkládat prostředky z účtu, který je registrován pod jejich vlastním jménem. 
<br /> 7.10.2. Nepřijímáme vklady třetí strany, např. od přátel, příbuzných, partnera, manžela nebo manželky.
<br /> 7.10.3. Pokud během našich pravidelných bezpečnostních kontrol zjistíme, že k tomuto došlo, všechny výhry v kasinu propadnou a budou poslány zpět do kasina a původní vklad bude poslán právoplatnému majiteli účtu / kreditní karty.
<br /> 7.10.47.10.4. Pokud je požadováno vrácení peníz právoplatnému majiteli pomocí bankovního převodu, všechny bankovní poplatky hradí příjemce.
<br /> 7.10.5. V případě provedení vkladu pomocí MasterCard, u nichž nejsou náhrady možné, majitel průkazu, musí majitel účtu podepsat „Formulář pro ověření kreditní karty“ a poslat nám doklady totožnosti pro ověření.
 <br /> 7.11 Minimální částka pro vyplacení je 100 EUR bankovním převodem nebo 50 EUR pro tzv. webwallets (webové peněženky).
<br /> 7.12 Všechny žádosti o odstoupení jsou na určitou dobu pozastaveny před tím, než jsou zpracovány. Během této krátké doby můžete svůj požadavek odstoupení od smlouvy zrušit a prostředky vám tak budou vráceny k disponibilnímu zůstatku na vašem účtu, aniž byste museli vložit novou zálohu. Vedení si vyhrazuje právo uhradit část nebo celou částku požadovanou při odstoupení zpět na kreditní kartu klienta, která byla použita k provedení vkladu.
<br /> 7.13 V souladu s našimi zásadami proti praní špinavých peněz musí být všechny vklady alespoň jednou použity v rámci sázení či hraní her, než je možné požádat o jejich zpětné vyplacení. Toto pravidlo se vztahuje i na stažené transakce.</p>
<p>7.14 V souladu s našimi zásadami proti peněžním podvodům si vyhrazujeme právo uhradit případné požadovaný výběr části či všech prostředků stejným způsobem platby, jakým byl uskutečněn jeden nebo více vkladů. Dále si vyhrazujeme právo na zaplacení jakéhokoliv požadovaného výběru přímo na váš bankovní účet.</p>
<p>7.15 &nbsp; Pokud vzniknou nějaké další náklady, či neočekávané poplatky při vyplacení na váš účet, vyhrazujeme si právo vám příslušné vynaložené částky naúčtovat.<br /> <br /></p>
<ol start="8">
<li><b> UZAVÍRÁNÍ SÁZEK A HRANÍ </b> </li>
</ol>
<p>8.1.&nbsp;&nbsp; &nbsp; Všechny transakce budou uzavřeny v jazyce, v němž jste umístili vaši transakci. <br />8.2.&nbsp;&nbsp; &nbsp; Je vaší povinností zajistit, aby údaje o každé transakci byli správné.
 <br />8.3.&nbsp;&nbsp; &nbsp; Na Webových stránkách máte přístup k transakční historii. 
<br />8.4.&nbsp;&nbsp; &nbsp; Vyhrazujeme si právo kdykoliv odmítnout jakoukoliv vámi požadovanou transakci nebo její část podle našeho vlastního uvážení. Nepřijmeme žádnou transakci, dokud od nás nedostanete potvrzení, že byla přijata. Pokud nedostanete potvrzení, že byla transakce přijata, kontaktujte Zákaznický servis. 
<br />8.5.&nbsp;&nbsp; &nbsp; Jakmile je vaše sázka potvrzena, nemůžete transakci zrušit bez našeho písemného souhlasu. <br />
8.6.&nbsp;&nbsp;&nbsp; Čas od času jsou vybraným hráčům  ExclusiveBet dostupné Bonusy.&nbsp;<b>&nbsp;</b></p>
<p><b> Bonusový vklad: </b> Všechny naše bonusy jsou typu tzv. cash back&ndash  - což znamená, že bonus bude připsán na pokrytí případné ztráty. Bonusy určené na Kasino musí být obecně vsazeny alespoň 40krát (pokud není uvedeno jinak), před tím, než je možné jakoukoliv část bonusového zůstatku proplatit, nebo přesunout jinam. Bonusy určené pro sportovní sázky, musí být obecně vsazeny alespoň 10krát. Kromě toho budou hráči moci vybrat pouze jednorázovou platbu s maximální výši desetinásobku původního vkladu v případě, že výhry vyplývají z hraní sportovního utkání nebo se jedná o tzv. cash back bonus. Částka převyšující tento limit propadá.&nbsp;<b>&nbsp;</b></p>
<p><b> Bonus volných prostředků:</b> Bonus je třeba vsadit alespoň 40krát před tím, než je možné jakoukoliv část bonusového zůstatku proplatit, nebo přesunout jinam. Navíc, hráči budou moci vybrat pouze jednorázovou platbu s minimální a maximální výší &euro;100 (nebo ekvivalent), a to pouze v případě, že výhry plynou z hraní s volnými prostředky bez nutnosti vkladu. Částka převyšující tento limit propadá.&nbsp;&euro;50 (nebo ekvivalent) je maximální částka, kterou lze vyplatit s využitím Bonusu volných prostředků free&nbsp;welcome&nbsp;bonus ve výši &nbsp;&euro;10 (nebo ekvivalent), není-li uvedeno jinak.&nbsp;<b>&nbsp;</b></p>
<p><b> Bonus volného otočení vkladu:</b> Bonus volného otočení vkladu (ať už s nutným vkladem nebo bez požadavku vkladu), jsou čas od času k dispozici pro vybrané ExclusiveBet hráče dle uvážení společnosti&rsquo;s.  Bonus volného otočení bez nutnosti vkládání prostředků bude připsán po úspěšné registraci. Bonus volného otočení s nutnosti vkládání prostředků bude připsán po prvním úspěšném vložení prostředků. Bonus volného otočení se musí použít do 48 hodin od okamžiku, kdy byl udělen. Bonus volného točení se přiděluje manuálně a není-li uvedeno jinak, toto přidělování může trvat až 24 hodin Bonus bez požadavku vkladu a až 48 hodin pro Bonus s požadavkem vkladu. Výhry z Bonusu volného točení musí být alespoň 40x vsazeny, pokud konkrétní nabídka nestanoví jinak. Hráči mají 2 dny od aktivace Bonusu volného otočení pro splnění požadavku vsazení Bonusu. Sázka musí proběhnout během 5 dnů pro splnění požadavků. Pokud platnost bonusu vyprší před uskutečněním sázky, či si hráč přeje vybrat peníze před splněním požadavků, Bonus propadne. Dále budou hráči schopni vybrat pouze jednorázovou platbu s minimální a maximální výší &nbsp;&euro;100 (nebo ekvivalent), a to pouze v případě&nbsp;, že výhry plynou z hraní s volnými prostředky bez nutnosti vkladu. Všeobecné obchodní podmínky ExclusiveBet se vztahují na všechny výše uvedené bonusy.</p>
<p>8.7&nbsp;&nbsp; Tímto dáváte souhlas s plněním platebních povinností, které vyplynou z vašeho jednání, v souladu s Podmínkami. Souhlasíte s tím, že nesete výhradní odpovědnost za jakékoli sázky na uskutečněné z Vašeho účtu.</p>
<p>8.8&nbsp;&nbsp; Jakmile jste umístili sázku a obdrželi jste potvrzení, že sázka byla přijata, je již nemožné sázku zrušit (je zcela na našem uvážení zda vás poskytne povolení tuto sázku zrušit nebo změnit).</p>
<p>8.9&nbsp;&nbsp; ExclusiveBet si vyhrazuje právo zadržet platbu a prohlásit sázky neplatné, máme-li důkazy o tom, že došlo k následující situaci: (i) souběh událostí byl zpochybněn; (ii) s cenou či cenami, nebo kulečníkovým stolem byl neoprávněně zacházeno; nebo (iii) došlo k ovlivňování výsledků, nebo k jakékoliv činnosti podle ustanovení 9.5. Jako důkaz o výše zmíněném může být brána velikosti, objem nebo struktura sázek s ExclusiveBet. Rozhodnutí vydané příslušným řídícím orgánem dotčeného sportu (pokud existuje) bude bráno jako rozhodující. Pokud některý zákazník dluží prostředky ExclusiveBet z jakéhokoli důvodu, máme právo tento fakt vzít v úvahu, před provedením jakékoli platby tomuto zákazníkovi.&nbsp;<br /> <br /></p>
<p>8.10&nbsp;&nbsp; Jestliže existují důkazy o sérii sázek, z nichž každá obsahuje stejný výběr či výběry a/nebo dle ustanovení 9.5 byly umístěny stejnou osobou či syndikátem jednotlivců pro téže osoby, ExclusiveBet si vyhrazuje právo zrušit platnost sázek a / nebo pozdržet výplatu výnosů do doby, než proběhne následné šetření. Za takovýchto okolností si ExclusiveBet také vyhrazuje právo zrušit účet a všechny související účty.</p>
<p>8.11&nbsp;&nbsp; Integrita sportovních utkání.&nbsp; Zavázali jsme se k zajištění integrity sportovních utkání a snažíme se identifikovat a vymýtit jakékoliv ovlivňování zápasů. Bez ohledu na jakékoli jiné ustanovení z těchto Ustanovení, nebo jakékoli ustanovení aktuálně platných Zásad ochrany osobních údajů tím, že provedete jakoukoliv sázku na Webových stránkách, výslovně berete na vědomí a souhlasíte s tím, že po celou dobu si vyhrazujeme právo podle vlastního uvážení nahlásit jakékoliv podezřelou sázkovou činnost sportovním federacím, regulačním orgánům, agenturám, komisím či sdružení (nebo jejich zástupcům), jak uznáme za vhodné, aby bylo možné identifikovat podezřelou sázkovou činnost a podporovat příslušná šetření. „Podezřelou sázkovou činností“ se rozumí činnost, která se, na základě našeho vlastního hodnocení, odchyluje od očekávaných sázek a zahrnuje, bez omezení: (i), neobvyklý a významný počet sázek pocházejících ze stejné geografické oblasti, nebo prostřednictvím propojených účtů; (Ii) sázející pokračuje v sázení za každou cenu, i když čelí postupnému poklesu příslušných kurzů; a / nebo (iii) jakýkoli jiný ukazatel, nebo vzorec chování, který dle našeho hodnocení svědčí o potenciálním ovlivňování zápasů, jakékoliv z dílčích ustanovení v rámci klauzule 9.5.  Přijmeme přiměřená obchodní opatření, která zajistí, že informace poskytované regulačním úřadům podle tohoto ustanovení podléhají smluvnímu ustanovení o mlčenlivosti, a že všechny poskytnuté informace nebo dokumenty musí být zničeny těmito regulačními orgány, pokud již nejsou relevantní v souvislosti s jakýmkoliv probíhajícím vyšetřováním, pátráním a disciplinárním řízením.</p>
<ol start="9">
<li><b>COLLUSION, CHEATING, FRAUD AND CRIMINAL ACTIVITY</b> </li>
</ol>
<p>9.1.&nbsp;&nbsp; &nbsp; Tyto následující činnosti nejsou dovoleny a představují závažné porušení podmínek: <br />&bull;&nbsp;&nbsp; &nbsp; domlouvaní se s třetími stranami;
 <br />&bull;&nbsp;&nbsp; &nbsp; použití neoprávněné výhodu nebo vlivu (běžně známého jako podvádění), včetně využívání jiných chyb, mezer nebo nedostatků našeho programu, použití automatizovaných hráčů (někdy nazývané jako „roboty“); nebo využívání z „chybného nastavení“;
 <br />&bull;&nbsp;&nbsp; &nbsp; provádění podvodných aktivit ve vlastní prospěch, včetně použití ukradených, kopírovaných nebo jinak neoprávněně získaných kreditních či debetních karet, jako zdroj finančních prostředků;
 <br />&bull;&nbsp;&nbsp; &nbsp; účast na případné trestné činnosti, včetně praní špinavých peněz a spáchání trestného činu s trestní následky. <br />9.2.&nbsp;&nbsp; &nbsp; Přijmeme veškerá přiměřená opatření k zabránění těchto činností, odhalení příslušných subjektů, náležité vypořádání se s příslušnými hráči. Neneseme zodpovědnost za jakékoli ztráty nebo škody, které mohou vzniknout vám nebo jakémukoliv jinému hráči v důsledku podvádění, podvodné nebo jinak nezákonné činnosti, a jakákoliv opatření podnikneme, záleží pouze na našem uvážení. <br />9.3.&nbsp;&nbsp; &nbsp; Máte-li podezření, že někdo nejedná podle ustanovených dohod, podvádí, nebo provádí nezákonnou činnost, musíte nám tento fakt co nejdříve oznámit posláním e-mailu. 
 <br />9.4.&nbsp;&nbsp; &nbsp; Vyhrazujeme si právo informovat příslušné orgány, jiné provozovatele on-line hracích serverů nebo provozovatelům hazardních her, ostatním poskytovatelům on-line služeb a bankám, společnostem vydávajícím kreditní karty, elektronickým poskytovatelům platebních nebo jiných finančních institucí o vaší totožnosti v případě jakékoliv podezření na nezákonné, podvodné nebo nepatřičné činnosti. Vy souhlasíte s tím, že budete plně spolupracovat při vyšetřování takovéto činnosti.</p>
<p>&nbsp;</p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 9.5&nbsp; Podezřelé sázky </p>
<p>a)&nbsp; Pro účely tohoto ustanovení 9.5 termín „Podezřelé sázky“ se vztahuje k situaci, kdy máme opodstatněné důvody se domnívat, že sázka nebo několik sázek byly vytvořeny za podezřelých okolností. Podezřelé sázky mimo jiné zahrnují:</p>
<p>i.&nbsp; situaci, kde je nadměrná frekvence a / nebo vysoce neobvyklé schéma sázek (ve srovnání s normami sázení) podána na stejném výběru či výběrech v krátkém časovém úseku;</p>
<p>ii.&nbsp; situaci, kde je nadměrná frekvence a / nebo vysoce neobvyklé schéma sázek na stejném výběru či výběrech, a kde je teoretická pravděpodobnost uvedeného výběru či výběrů na vítězství v době podání sázky, na základě nabízených kurzů v době podání sázky, a kde tato hlediska jsou do značné míry v rozporu s teoretickou pravděpodobností téhož výběru či výběrů na výhru při porovnání jejich výchozích cen,</p>
<p>iii.&nbsp; situaci, kde integrita události (nebo událostí) byla zpochybněna, včetně například tam, kde jeden (nebo více) účastníků prokázal neobyčejnou zdatnost, o níž my se domníváme, že jste buď vy, nebo někdo známý věděl v době podání sázky, a která ale byla skryta před širokou veřejností s cílem získat výhodu v jakékoli sázkové činnosti na tuto sportovní událost (nebo tyto události);</p>
<p>iv.&nbsp; situaci, kde máme důvodné podezření, že sázka nebo řetězec propojených sázek byl umístěn roboticky, automatizovanými prostředky, či způsobem jiným, než prostřednictvím manuálním zadání každé sázky držitelem účtu;</p>
<p>v.&nbsp; situaci, kde se domníváme, že jste využili neférových vnějších faktorů nebo vlivů spojené s událostí či událostmi, které jsou předmětem jakékoliv sázky;</p>
<p>vi.&nbsp; situaci, kde máme oprávněné podezření, že jste si otevřeli duplicitní účty nebo tam, kde máme oprávněné podezření, že požíváte druhý nebo i jiné účty spolu s vaším účtem s cílem utajit skutečnou hodnotu, povahu nebo charakter sázek, které podáváte vy nebo jsou podávány pod vaším jménem, a to i tehdy, kdy druhý nebo každý další účet jsou otevřeny pod různými jmény;</p>
<p>vii.&nbsp; situaci, kde máme důvod věřit, že jednáte po dohodě s ostatními, nebo že nejednáte sami za sebe; nebo </p>
<p>viii.&nbsp; situaci, kde se domníváme, že sázky byly umístěny z místa nebo zařízení jiného než ze z místa či zařízení, které jste použili pro podání sázky.</p>
<p>10.&nbsp; <b> DALŠÍ NEPOVOLENÉ AKTIVITY </b></p>
<p>10.1.&nbsp;&nbsp; &nbsp; Neměli byste používat Webové stránky pro jakýkoliv jednání, které je považováno za hanlivé, urážlivé, obscénní, rasistické, sexistické, diskriminační, nebo útočné. Nesmíte používat urážlivý nebo agresivní jazyk či vyobrazení; nadávat, vyhrožovat, obtěžovat či zneužívat jiné osoby, včetně jiných uživatelů, nebo se chovat takovým způsobem vůči jakémukoliv zaměstnanci společnosti, kteří pracují pro Webové stránky nebo pro Zákaznický servis. <br />10.2.&nbsp;&nbsp; &nbsp; Nebudete poškozovat Webové stránky, zaplavovat webové stránky s informacemi, což by mohlo omezit jejich funkčnost, ani nebudete v žádném případě používat funkce, které mohou mít vliv na funkci webových stránek jako například šíření virů, „worms“, „logical bombs“ nebo podobné. Jakékoliv zmnožené transakce nebo „spam“ jsou přísně zakázány. Nesmíte zasahovat nebo jakkoliv manipulovat, odstraňovat nebo jakýmkoliv způsobem měnit jakékoli informace v jakékoli formě, která je obsažena na těchto stránkách. <br />10.3.&nbsp;&nbsp; &nbsp; Budete používat webové stránky pouze pro osobní zábavu. Není povoleno reprodukovat webové stránky nebo jakékoli jejich části v jakékoli formě, bez našeho výslovného souhlasu. <br />10.4.&nbsp;&nbsp; &nbsp; . Je zakázáno získávat neoprávněného přístupu k webovým stránkám, serverům, na kterém je webová stránka uložena, nebo jakýkoliv server, počítač nebo databázi připojené na webové stránky. Je zakázáno útočit na webové stránky prostřednictvím útoku denial-of-service a podobně. Při porušení tohoto ustanovení budeme hlásit každé takovéto porušení příslušným orgánům činným v trestním řízení a budeme spolupracovat s těmito orgány tím, že jim zveřejníme vaší totožnost. V případě takového porušení bude okamžitě ukončeno vaše právo na používání webových stránek. <br />10.5.&nbsp;&nbsp; &nbsp; Neneseme odpovědnost za jakékoli ztráty nebo škody způsobené distribucí útoku typu denial-of-service, šířením virů nebo jiných technologicky škodlivých materiálů, které mohou infikovat počítače, počítačové programy, data nebo jiné osobní materiály z důvodu vašeho používání Webových stránek z důvodu vašeho stahování materiálů, zveřejněných na takovýchto webových stránkách, nebo na jakékoliv webové stránce napojené na internetovou stránku. <br />10.6.&nbsp;&nbsp; &nbsp; Je zakázáno prodávat nebo převádět účty mezi hráči.</p>
 <p>11.&nbsp; <b> ZNEUŽITÍ BONUSŮ </b></p>
<p class="content-page">11.1. ExclusiveBet oceňuje hráče, kteří jeho služby využívají jako způsob zábavy Bonusy a vstupem do vybraných akcích v dobré víře a jako projev uznání za loajalitu. Volné sázení, bonusy a jiné akce budou zrušeny, odepřeny nebo odebrány hráčům, kteří této nabídky zneužívají. Vyhrazujeme si právo zrušit / odejmout bonusovou nabídku kdykoliv v případě jakéhokoli podezření na zneužití nabídky a ukončit účet daného hráče s okamžitou platností. ExclusiveBet si vyhrazuje právo stíhat daného hráče. &lsquo;Zneužití&rsquo zahrnuje, ale není omezeno, na otevírání více účtů za účelem požadování více bonusů.  Dále, jestliže je nějaká z podmínek nabídky bonusů nebo marketingové akce porušena nebo pokud existuje důvodné podezření ze strany ExclusiveBet, že série sázek byla zákazníkem nebo skupinou zákazníků vytvořena za účelem získání bonusu, volných sázek nebo jakékoliv jiné reklamní nabídce, zaručující zákazníkův jistý zisk bez ohledu na výsledek, ať už samostatně nebo jako součást skupiny, ExclusiveBet si vyhrazuje právo na odejmutí bonusu a je zcela na jeho uvážení, zda vyhodnotí sázky dle existujících kurzů, zruší volné sázky a / nebo jakékoli sázky financované z prémie nebo prémiové výhry.  Vyhrazujeme si právo zrušit bonus, který jste obdrželi jako odměnu za vklad, pokud vklad nebyl použit k sázení. Vyhrazujeme si právo zrušit bonus a všechny výhry spojené se sázením uskutečněné s použitím bonusu či jeho části v případě, že máme podezření, že došlo k zneužití bonusu. ExclusiveBet si vyhrazuje právo kdykoli požadovat důkaz o vaší totožnosti, věku a původu finančních prostředků, včetně předtím, než je bonus připsán na vás účet.</p>
<p>12.&nbsp; <b>UZAVŘENÍ A UKONČENÍ Z NAŠÍ STRANY </b></p>
<p>12.1.&nbsp;&nbsp; &nbsp; Váš neaktivní účet bude ukončen písemným oznámením (nebo pokusem o oznámení), pomocí kontaktních údajů. V případě takového ukončení z naší strany, krom důvodů pro ukončení vyjmenovaných podle odstavce 11 (tajná dohoda, podvádění, podezřelé sázky, podvody a trestná činnosti), nebo podle odstavce 20 (porušení Podmínek) těchto Podmínek, vám vrátíme zůstatek vašeho účtu. Pokud vás nelze nalézt, finanční prostředky budou poukázány příslušnému orgánu, pod nějž příslušností hazardu spadá.</p>
<p class="content-page">12.2. Vyhrazujeme si právo kdykoliv uzavřít váš účet.</p>
<p class="content-page">12.3. Nebudeme tolerovat žádné urážlivé, hanlivé nebo násilné chování vůči některému z našich zaměstnanců. Pokud se takto chováte, (což bude posouzeno výhradně námi), vyhrazujeme si právo pozastavit a / nebo zrušit váš účet, a / nebo přijmout jiná opatření, dle vlastního uvážení.</p>
<p>13.&nbsp; <b> ZMĚNY NA WEBU </b></p>
<p>13.1.&nbsp;&nbsp; &nbsp; Dle vlastního uvážení můžeme kdykoliv měnit obsah nebo změnit jakýkoliv produkt nabízený prostřednictvím Webových stránek za účelem udržování Webové stránky. &nbsp;</p>
<p>14.&nbsp; <b> SELHÁNÍ IT TECHNOLOGIE </b></p>
<p>14.1.&nbsp;&nbsp; &nbsp; V případě neočekávané systémové vady, poruchy nebo vyskytující se chyby v softwaru nebo hardwaru, který používáme, učiníme okamžité kroky k nápravě tohoto problému. <br /> 14.2.&nbsp;&nbsp; &nbsp; Nepřijímáme žádnou odpovědnost za selhání IT, které jsou způsobeny vaším vybavení používaného pro přístup na Webové stránky, nebo chyby, které se týkají vašeho poskytovatele internetových služeb.</p>
<p>15.&nbsp; <b> CHYBY NEBO OPOMENUTÍ </b></p>
<p>15.1.&nbsp;&nbsp; &nbsp; Řada okolností může zapříčinit vznik chyby z naší strany v době uzavírání sázky nebo platby.<br /> 15.2.&nbsp;&nbsp; &nbsp; Exbeteu.com si vyhrazuje právo zrušit jakoukoli sázku provedenou na zjevně nesprávné kurzy, přehozené kurzy (kde se uvedené kurzy týkají špatných týmů), nebo pokud je sázka podána až po začátku události, pokud daná událost není k dispozici pro on-line sázky. exbeteu.com si vyhrazuje právo odmítnout, omezit, zrušit nebo omezit všechny sázky.
<br /> 15.3.&nbsp;&nbsp; &nbsp; Ani my (včetně našich zaměstnanců nebo zástupců), ani naši smluvní partneři nebo dodavatelé nenesou zodpovědnost za jakékoliv ztráty, včetně ztráty výher, které vyplývají z chyb z naší strany či vašeho omylu. Jakékoliv výhry / ztráty vycházející z takovéto chyby vám budou odebrány.</p>
<p>16.&nbsp; <b> VYLOUČENÍ ODPOVĚDNOSTI </b></p>
<p>16.1.&nbsp;&nbsp; &nbsp; Váš přístup a využívání produktů nabízených prostřednictvím Webové stránky je výlučně věcí vaší volby, vašeho zvážení a na vaší vlastní zodpovědnost.<br /> 16.2.&nbsp;&nbsp; &nbsp; Poskytneme odpovídající péči a servis Webovým stránkám tak, jak je popsáno v těchto Podmínkách. Neslibujeme nic jiného, ani neposkytujeme žádné další záruky vztahující se na Webové stránky samotné, nebo na výrobky nabízené prostřednictvím Webových stránek, a tímto vylučujeme (v rozsahu povoleném zákonem) veškeré záruky týkající se téhož.<br /> 16.3.&nbsp;&nbsp; &nbsp; Neneseme odpovědnost vůči Vám v rámci smlouvy, deliktu (včetně nedbalosti) nebo jakékoliv obchodní ztráty, včetně ztráty dat, zisku, příjmů, podnikání, příležitostí, dobrého jména, pověsti nebo přerušení činnosti, nebo jakékoliv ztráty, které nejsou v současné době předvídatelné, jak vyplývá z Podmínek nebo z vašeho používání webových stránek.</p>
<p>17.&nbsp; <b> PORUŠENÍ PODMÍNEK </b></p>
<p>17.1.&nbsp;&nbsp; &nbsp; Budete nám kompenzovat jakékoliv nároky, závazky, náklady, náklady (včetně právních poplatků) a jiných poplatků, které mohou vzniknout v důsledku vašeho porušení podmínek v plné výši.<br /> 17.2.&nbsp;&nbsp; &nbsp; Pokud jste vážně porušili smluvní podmínky, vyhrazujeme si právo, ale nikoliv povinnost:
<br /> 17.2.1.&nbsp;&nbsp; &nbsp; Poskytnout vám oznámení (prostřednictvím udaných kontaktních údajů), že jste se dostali do rozporu s Podmínkami, které vyžadují přerušení činnosti nebo naopak nekonání,
<br /> 17.2.2.&nbsp;&nbsp; &nbsp; . Pozastavit váš účet tak, abyste nebyli schopni uzavírat sázky nebo hrát na Webových stránkách,
 <br /> 17.2.3.&nbsp;&nbsp; &nbsp; Zrušit váš účet buď na základě předchozího upozornění, či bez něj.
<br /> 17.2.4.&nbsp;&nbsp; &nbsp; Vybrat z vašeho účtu částku všech výplat, bonusů nebo výher, kterých se porušení podmínek týká. 
<br /> 17.3.&nbsp;&nbsp; &nbsp; Vyhrazujeme si právo zakázat jakékoliv přístupové údaje a přístupové heslo, pokud jste podle našeho názoru porušili některé z ustanovení těchto Podmínek.</p>
<p>18.&nbsp; <b> PRÁVA K DUŠEVNÍMU VLASTNICTVÍ </b></p>
<p>18.1.&nbsp;&nbsp; &nbsp; Webový design, text, grafika, hudba, zvuk, fotografie, video, výběr a uspořádání výše zmíněných, softwarový balíček, základní zdrojový kód, software a všechny ostatní materiály obsažené v rámci těchto stránek podléhají autorskému právu a dalším vlastnickým právům, které buď patří nám, nebo jsou používány na základě licence od držitelů práv třetích stran. Vzhledem k tomu, že jakýkoliv materiál obsažený na webových stránkách je možné stáhnout nebo vytisknout, tento materiál lze stáhnout pouze do jednoho osobního počítače a kopie dokumentů či jejich části mohou být vytištěny pouze a výhradně pro vlastní potřebu a nekomerční použití.
<br /> 18.2.&nbsp;&nbsp; &nbsp; Za žádných okolností nesmí využití Webových stránek nést zisk v rámci jakýchkoli práv duševního vlastnictví (například autorských práv, know-how nebo ochranné známky), které patří nám či třetí straně.
<br /> 18.3.&nbsp;&nbsp; &nbsp; Není možné za žádných okolností dále v
