<p>Je nelegálne pre každého, kto je mladší ako 18 rokov, aby si otvoril účet a hral na stránke  [Metadata:htmlencode(/Metadata/Settings.Operator_DisplayName)]. Vykonávame kontrolu veku u všetkých zákazníkov, ktorí použijú mechanizmy platby dostupné neplnoletým osobám a k tomu vykonávame náhodné kontroly veku vykonávané inými spôsobmi. Vyhradzujeme si právo požiadať vás o dokument, ktorý overí váš vek, váš účet bude pozastavený, kým nepotvrdíte svoj vek.</p>
<p>&nbsp;</p>
<p>Ak zdieľate váš počítač s priateľmi alebo rodinou, ktorí nemajú vek na otvorenie účtu, prosím zvážte rodičovské filtre, tento software umožňuje rodičom regulovať prístup na internet a zamedziť  deťom prístup na stránky s hazardným obsahom.</p>
<p>&nbsp;</p>
<p>Net Nanny&trade; www.netnanny.com</p>
<p>CyberPatrol www.cyberpatrol.com</p>
