<p>Vážený/á &#160; $USERNAME$,<br />
<br />
vaše výbery dosiahli celkovej hodnoty 2300. Aby sme dodržali maltské a európske zákony na ochranu pred praním špinavých peňazí a financovania terorizmu, musíme v takomto prípade overiť vašu totožnosť. Proti praniu špinavých peňazí preverujeme všetky zákaznicke transakcie. S overením ste zároveň súhlasili prijatím zmluvných podmienok.
<br />Na adresu <a href="mailto:[Metadata:htmlencode(/Metadata/Settings.Email_SupportAddress)]">[Metadata:htmlencode(/Metadata/Settings.Email_SupportAddress)]</a> prosím zašlite kópiu preukazu totožnosti, napríklad pasu alebo občianskeho preukazu. Po overení bude váš výber okamžite spracovaný.
<br />Ak doklady pre overenie neposkytnete, váš účet bude pozastavený alebo trvale zatvorený. <br />S pozdravom,<br />
[Metadata:htmlencode(/Metadata/Settings.Operator_DisplayName)] tím
