<p>Ahoj $FIRSTNAME$,</p>

<p>týmto potvrzujeme, že vaša e-mailová adresa [Metadata:htmlencode(/Metadata/Settings.Operator_DisplayName)] bola zmenená.</p>
<p>Ak ste o zmenu nežiadali, ihneď nás prosím kontaktujte na <a href="mailto:[Metadata:htmlencode(/Metadata/Settings.Email_SupportAddress)]">[Metadata:htmlencode(/Metadata/Settings.Email_SupportAddress)]</a></p>
<p>S pozdravom, <br /> [Metadata:htmlencode(/Metadata/Settings.Operator_DisplayName)] Oddelenie zákaznickych služieb</p>


