<p>Vážený zákazník,</p>
<p></p>
<p>
aktualizovali sme naše <a href="[Metadata:value(/Metadata/Settings.Terms_Conditions_Url)]" >Pravidlá a predpisy</a>.
 Uisťujeme vás však, že zmeny nemajú vplyv na váš herný zážitok ani zákaznický vzťah voči nám. Pred ďalšou hrou však potrebujeme, aby ste podmienky prijali.
</p>
<p>
 Ak máte nejaké otázky, neváhajte nás kontaktovať.
 </p>
 <p>
 <br />
 Ďakujeme, <br />
oddelenie zákazníckej podpory
</p>
