Vaše výbery dosiahli celkovej hodnoty viac ako 2.300 EUR a podľa regulačných nariadení musíme pred ďalším výberom overiť váš účet. Na túto adresu <a href="mailto:[Metadata:htmlencode(/Metadata/Settings.Email_SupportAddress)]">[Metadata:htmlencode(/Metadata/Settings.Email_SupportAddress)]</a>
prosím zašlite následujúce dokumenty <p>a) overenie adresy (účet za energie nebo výpis z účtu) </p>
<p>b) kópia občianskeho preukazu alebo cestovného pasu</p>
<p>c) kópia karty použitej ku vkladu</p>

