Entropay je predplatená, virtuálna VISA karta, ktorá môže byť použitá všade tam, kde on-line VISA je akceptovaná. Môžete si pridať finančné prostriedky na kartu VISA Entropay kreditnou alebo debetnou kartou, alebo prostredníctvom miestneho bankového prevodu.<br /><br />
Registering and funding an EntroPay VISA card only takes a few moments, after which you can use your EntroPay prepaid VISA card immediately !

<a href="https://secure2.entropay.com/processes/upaffiliatelanding/unprot/affiliatewelcome.do?referrerID={0}" target="_blank">Click here</a> to Open and EntroPay account.
