AstroPayCard je predplatná, virtuálna VISA karta ktorá môže byť použitá kdekoľvek kde je akceptovaná VISA. Pridať prostriedky na vašu AstroPayCard môžete s vašou platobou katrou alebo bankovým prevodom.<br /><br />
Zaregistrovanie AstroPayCard VISA trvá iba chvíľu a hneď ju môžete používať!

<a href="https://astropaycard.com/index/register" target="_blank">Kliknite sem</a> pre založenie AstroPayCard účtu.
