<p>Milý $USERNAME$,</p>
<br /> Ďakujeme za kontaktovanie [Metadata:htmlencode(/Metadata/Settings.Operator_DisplayName)]<br /> <br /> Váš limit pre vklad bol nastavený na &nbsp;$NEWLIMITAMOUNT$ $NEWLIMITPERIOD$. <br /> <br /> Limit si môžete ihneď znížiť &nbsp;pomocou rovnakého menu v časti zodpovedné hranie. <br /> <br /> Avšak, ak chcete zvýšiť svoj limit, bude to trvať 7 dní pred aktiváciou nového limitu. 7 dňová lehota je daná z dôvodu poskytnuťia Vám dostatok času na zváženie.<br /> <br /> Prosím, neváhajte nás kontaktovať, ak máte nejaké otázky na <a href="mailto:[Metadata:htmlencode(/Metadata/Settings.Email_SupportAddress)]">[Metadata:htmlencode(/Metadata/Settings.Email_SupportAddress)]</a>
<p>&nbsp;</p>
<p>Kind Regards</p>
<p>[Metadata:htmlencode(/Metadata/Settings.Operator_DisplayName)] Zákaznícka Podpora&nbsp;&nbsp;&nbsp;</p>
