Vymeňte vaše peniaze za Ukash poukážku. Použite ho na platbu online, je to veľmi jednoduché! Nepotrebujete nám dať vaše osobné finančné údaje. Takisto ani vôbec nepotrebujete platobnú kartu. <br />
<a href="https://direct.ukash.com/forexViewer/ExchangeRates.aspx" target="_blank">Zobraziť výmenne kurzy pre Ukash</a><br/>
Môžete kontaktovať Ukash zákaznícke centrum  <a href="https://www.ukash.com/en-GB/support/contact/" target="_blank">na tomto linku</a>  ak máte nejaké otázky.
