<p>Vážený/á $USERNAME$,<br /> </p>
<br />
tento e-mail potvrdzuje, že na vašom účte bolo do $DATE$ aktivované sebavylúčenie.
<br /><br />
Počas tejto doby sa nemôžete na účet prihlásiť. Po uplynutí lehoty vás upozorníme e-mailom.
<br /><br />
Ak máte nejaké otázky, obráťte sa prosím na <a href="mailto:[Metadata:htmlencode(/Metadata/Settings.Email_SupportAddress)]">[Metadata:htmlencode(/Metadata/Settings.Email_SupportAddress)]</a><p>&#160;</p><p><br />S pozdravom</p><p>[Metadata:htmlencode(/Metadata/Settings.Operator_DisplayName)] Oddelenie zákazníckej podpory</p>
