Pomocou menu nižšie si teraz môžete nastaviť, za koľko môžete denne, týždenne a mesačne staviť. Tieto limity sú nezávislé na limitoch nebo minimálnych sumách uvedených u jednotlivých metód. Po nastavení limitu dostanete e-mailom potvrdenie. Svoj limit môžete kedykoľvek znížiť. Pokiaľ si budete priať limit zvýšiť, musíte počkať na uplynutie lehoty 7 dní (počas tejto lehoty máte stále možnosť si zmenu rozmyslieť). Upozorňujeme, že tento limit platí iba pre Kasíno hry.


