<p>Vážený/á $USERNAME$, <br />
</p><br />
týmto potvrdzujeme, že obdobie vášho sebavylúčenia bolo teraz ukončené a vy sa opät môžete prihlásiť na svoj účet. <br />
<br />Ak máte nejaké otázky, obráťte sa prosím na <a href="mailto:[Metadata:htmlencode(/Metadata/Settings.Email_SupportAddress)]">[Metadata:htmlencode(/Metadata/Settings.Email_SupportAddress)]</a><p>&#160;</p><p><br />S pozdravom</p><p>[Metadata:htmlencode(/Metadata/Settings.Operator_DisplayName)] Oddelenie zákazníckej podpory</p>
