<p>Požiadali ste o zmenu e-mailovej adresy [Metadata:htmlencode(/Metadata/Settings.Operator_DisplayName)]. Na novú adresu ($EMAIL$) bol odoslaný overovací e-mail.</p>
<p>Ak ste o zmenu nežiadali, ihneď sa na nás prosím obráťte na <a href="mailto:[Metadata:htmlencode(/Metadata/Settings.Email_SupportAddress)]">[Metadata:htmlencode(/Metadata/Settings.Email_SupportAddress)]</a></p>
<p>S pozdravom, <br /> [Metadata:htmlencode(/Metadata/Settings.Operator_DisplayName)] Oddelenie zákaznickych služieb</p>
